/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt;

import jolt.math.Vec3;

public class ConeConstraint extends TwoBodyConstraint {

    private Vec3 Vec3_TEMP_GEN_0;

    static public final ConeConstraint T_01 = new ConeConstraint((byte) 1, (char) 1);

    static public final ConeConstraint T_02 = new ConeConstraint((byte) 1, (char) 1);

    static public final ConeConstraint T_03 = new ConeConstraint((byte) 1, (char) 1);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public ConeConstraint(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public void SetHalfConeAngle(float inHalfConeAngle) {
        internal_native_SetHalfConeAngle(native_address, inHalfConeAngle);
    }

    /*[-JNI;-NATIVE]
ConeConstraint* nativeObject = (ConeConstraint*)this_addr;
nativeObject->SetHalfConeAngle((float)inHalfConeAngle);
*/
    public static native void internal_native_SetHalfConeAngle(long this_addr, float inHalfConeAngle);

    public float GetCosHalfConeAngle() {
        return internal_native_GetCosHalfConeAngle(native_address);
    }

    /*[-JNI;-NATIVE]
ConeConstraint* nativeObject = (ConeConstraint*)this_addr;
return nativeObject->GetCosHalfConeAngle();
*/
    public static native float internal_native_GetCosHalfConeAngle(long this_addr);

    public Vec3 GetTotalLambdaPosition() {
        long pointer = internal_native_GetTotalLambdaPosition(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_0.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ConeConstraint* nativeObject = (ConeConstraint*)this_addr;
static Vec3 copy_addr;
copy_addr = nativeObject->GetTotalLambdaPosition();
return (jlong)&copy_addr;*/
    public static native long internal_native_GetTotalLambdaPosition(long this_addr);

    public float GetTotalLambdaRotation() {
        return internal_native_GetTotalLambdaRotation(native_address);
    }

    /*[-JNI;-NATIVE]
ConeConstraint* nativeObject = (ConeConstraint*)this_addr;
return nativeObject->GetTotalLambdaRotation();
*/
    public static native float internal_native_GetTotalLambdaRotation(long this_addr);
}
