/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt;

import jolt.idl.IDLBase;

public class HeightFieldShapeConstantValues extends IDLBase {

    static public final HeightFieldShapeConstantValues T_01 = new HeightFieldShapeConstantValues((byte) 1, (char) 1);

    static public final HeightFieldShapeConstantValues T_02 = new HeightFieldShapeConstantValues((byte) 1, (char) 1);

    static public final HeightFieldShapeConstantValues T_03 = new HeightFieldShapeConstantValues((byte) 1, (char) 1);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public HeightFieldShapeConstantValues(byte b, char c) {
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
HeightFieldShapeConstantValues* nativeObject = (HeightFieldShapeConstantValues*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public static float get_cNoCollisionValue() {
        return internal_native_get_cNoCollisionValue();
    }

    /*[-JNI;-NATIVE]
return HeightFieldShapeConstantValues::cNoCollisionValue;
*/
    public static native float internal_native_get_cNoCollisionValue();
}
