/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt;

import jolt.idl.IDLBase;

public class SimShapeFilter extends IDLBase {

    static public final SimShapeFilter T_01 = new SimShapeFilter((byte) 1, (char) 1);

    static public final SimShapeFilter T_02 = new SimShapeFilter((byte) 1, (char) 1);

    static public final SimShapeFilter T_03 = new SimShapeFilter((byte) 1, (char) 1);

    public SimShapeFilter() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new SimShapeFilter();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public SimShapeFilter(byte b, char c) {
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
SimShapeFilter* nativeObject = (SimShapeFilter*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
