/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt;

import com.github.xpenatan.jParser.idl.IDLBase;

public class TireMaxImpulseCallbackResult extends IDLBase {

    static public final TireMaxImpulseCallbackResult NULL = TireMaxImpulseCallbackResult.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected TireMaxImpulseCallbackResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static TireMaxImpulseCallbackResult native_new() {
        return new TireMaxImpulseCallbackResult((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
TireMaxImpulseCallbackResult* nativeObject = (TireMaxImpulseCallbackResult*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public float get_mLongitudinalImpulse() {
        return internal_native_get_mLongitudinalImpulse(native_address);
    }

    /*[-JNI;-NATIVE]
TireMaxImpulseCallbackResult* nativeObject = (TireMaxImpulseCallbackResult*)this_addr;
return nativeObject->mLongitudinalImpulse;
*/
    public static native float internal_native_get_mLongitudinalImpulse(long this_addr);

    public void set_mLongitudinalImpulse(float mLongitudinalImpulse) {
        internal_native_set_mLongitudinalImpulse(native_address, mLongitudinalImpulse);
    }

    /*[-JNI;-NATIVE]
TireMaxImpulseCallbackResult* nativeObject = (TireMaxImpulseCallbackResult*)this_addr;
nativeObject->mLongitudinalImpulse = mLongitudinalImpulse;
*/
    public static native void internal_native_set_mLongitudinalImpulse(long this_addr, float mLongitudinalImpulse);

    public float get_mLateralImpulse() {
        return internal_native_get_mLateralImpulse(native_address);
    }

    /*[-JNI;-NATIVE]
TireMaxImpulseCallbackResult* nativeObject = (TireMaxImpulseCallbackResult*)this_addr;
return nativeObject->mLateralImpulse;
*/
    public static native float internal_native_get_mLateralImpulse(long this_addr);

    public void set_mLateralImpulse(float mLateralImpulse) {
        internal_native_set_mLateralImpulse(native_address, mLateralImpulse);
    }

    /*[-JNI;-NATIVE]
TireMaxImpulseCallbackResult* nativeObject = (TireMaxImpulseCallbackResult*)this_addr;
nativeObject->mLateralImpulse = mLateralImpulse;
*/
    public static native void internal_native_set_mLateralImpulse(long this_addr, float mLateralImpulse);
}
