/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.core;

import jolt.idl.IDLBase;
import jolt.math.Vec4;

public class Color extends IDLBase {

    private Color Color_TEMP_GEN_0;

    private Vec4 Vec4_TEMP_GEN_0;

    static private Color Color_TEMP_STATIC_GEN_0;

    static private Color Color_TEMP_STATIC_GEN_1;

    static private Color Color_TEMP_STATIC_GEN_2;

    static private Color Color_TEMP_STATIC_GEN_3;

    static private Color Color_TEMP_STATIC_GEN_4;

    static private Color Color_TEMP_STATIC_GEN_5;

    static private Color Color_TEMP_STATIC_GEN_6;

    static private Color Color_TEMP_STATIC_GEN_7;

    static private Color Color_TEMP_STATIC_GEN_8;

    static private Color Color_TEMP_STATIC_GEN_9;

    static private Color Color_TEMP_STATIC_GEN_10;

    static private Color Color_TEMP_STATIC_GEN_11;

    static private Color Color_TEMP_STATIC_GEN_12;

    static private Color Color_TEMP_STATIC_GEN_13;

    static private Color Color_TEMP_STATIC_GEN_14;

    static public final Color NULL = Color.native_new();

    static public final Color T_01 = Color.native_new();

    static public final Color T_02 = Color.native_new();

    static public final Color T_03 = Color.native_new();

    public Color() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new Color();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected Color(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static Color native_new() {
        return new Color((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
Color* nativeObject = (Color*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public Color MulColor(Color other) {
        long pointer = internal_native_MulColor(native_address, other.native_address);
        if (pointer == 0)
            return null;
        if (Color_TEMP_GEN_0 == null)
            Color_TEMP_GEN_0 = Color.native_new();
        Color_TEMP_GEN_0.internal_reset(pointer, false);
        return Color_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
Color* nativeObject = (Color*)this_addr;
static Color copy_addr;
copy_addr = (*nativeObject * *((Color* )other_addr));
return (jlong)&copy_addr;*/
    public static native long internal_native_MulColor(long this_addr, long other_addr);

    public Vec4 ToVec4() {
        long pointer = internal_native_ToVec4(native_address);
        if (pointer == 0)
            return null;
        if (Vec4_TEMP_GEN_0 == null)
            Vec4_TEMP_GEN_0 = Vec4.native_new();
        Vec4_TEMP_GEN_0.internal_reset(pointer, false);
        return Vec4_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
Color* nativeObject = (Color*)this_addr;
static Vec4 copy_addr;
copy_addr = nativeObject->ToVec4();
return (jlong)&copy_addr;*/
    public static native long internal_native_ToVec4(long this_addr);

    public int get_mU32() {
        return internal_native_get_mU32(native_address);
    }

    /*[-JNI;-NATIVE]
Color* nativeObject = (Color*)this_addr;
return nativeObject->mU32;
*/
    public static native int internal_native_get_mU32(long this_addr);

    public void set_mU32(int mU32) {
        internal_native_set_mU32(native_address, mU32);
    }

    /*[-JNI;-NATIVE]
Color* nativeObject = (Color*)this_addr;
nativeObject->mU32 = mU32;
*/
    public static native void internal_native_set_mU32(long this_addr, int mU32);

    public static Color get_sBlack() {
        long pointer = internal_native_get_sBlack();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_0 == null)
            Color_TEMP_STATIC_GEN_0 = Color.native_new();
        Color_TEMP_STATIC_GEN_0.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_0;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sBlack;
*/
    public static native long internal_native_get_sBlack();

    public static Color get_sDarkRed() {
        long pointer = internal_native_get_sDarkRed();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_1 == null)
            Color_TEMP_STATIC_GEN_1 = Color.native_new();
        Color_TEMP_STATIC_GEN_1.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_1;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sDarkRed;
*/
    public static native long internal_native_get_sDarkRed();

    public static Color get_sRed() {
        long pointer = internal_native_get_sRed();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_2 == null)
            Color_TEMP_STATIC_GEN_2 = Color.native_new();
        Color_TEMP_STATIC_GEN_2.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_2;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sRed;
*/
    public static native long internal_native_get_sRed();

    public static Color get_sDarkGreen() {
        long pointer = internal_native_get_sDarkGreen();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_3 == null)
            Color_TEMP_STATIC_GEN_3 = Color.native_new();
        Color_TEMP_STATIC_GEN_3.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_3;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sDarkGreen;
*/
    public static native long internal_native_get_sDarkGreen();

    public static Color get_sGreen() {
        long pointer = internal_native_get_sGreen();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_4 == null)
            Color_TEMP_STATIC_GEN_4 = Color.native_new();
        Color_TEMP_STATIC_GEN_4.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_4;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sGreen;
*/
    public static native long internal_native_get_sGreen();

    public static Color get_sDarkBlue() {
        long pointer = internal_native_get_sDarkBlue();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_5 == null)
            Color_TEMP_STATIC_GEN_5 = Color.native_new();
        Color_TEMP_STATIC_GEN_5.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_5;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sDarkBlue;
*/
    public static native long internal_native_get_sDarkBlue();

    public static Color get_sBlue() {
        long pointer = internal_native_get_sBlue();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_6 == null)
            Color_TEMP_STATIC_GEN_6 = Color.native_new();
        Color_TEMP_STATIC_GEN_6.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_6;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sBlue;
*/
    public static native long internal_native_get_sBlue();

    public static Color get_sYellow() {
        long pointer = internal_native_get_sYellow();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_7 == null)
            Color_TEMP_STATIC_GEN_7 = Color.native_new();
        Color_TEMP_STATIC_GEN_7.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_7;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sYellow;
*/
    public static native long internal_native_get_sYellow();

    public static Color get_sPurple() {
        long pointer = internal_native_get_sPurple();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_8 == null)
            Color_TEMP_STATIC_GEN_8 = Color.native_new();
        Color_TEMP_STATIC_GEN_8.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_8;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sPurple;
*/
    public static native long internal_native_get_sPurple();

    public static Color get_sCyan() {
        long pointer = internal_native_get_sCyan();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_9 == null)
            Color_TEMP_STATIC_GEN_9 = Color.native_new();
        Color_TEMP_STATIC_GEN_9.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_9;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sCyan;
*/
    public static native long internal_native_get_sCyan();

    public static Color get_sOrange() {
        long pointer = internal_native_get_sOrange();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_10 == null)
            Color_TEMP_STATIC_GEN_10 = Color.native_new();
        Color_TEMP_STATIC_GEN_10.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_10;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sOrange;
*/
    public static native long internal_native_get_sOrange();

    public static Color get_sDarkOrange() {
        long pointer = internal_native_get_sDarkOrange();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_11 == null)
            Color_TEMP_STATIC_GEN_11 = Color.native_new();
        Color_TEMP_STATIC_GEN_11.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_11;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sDarkOrange;
*/
    public static native long internal_native_get_sDarkOrange();

    public static Color get_sGrey() {
        long pointer = internal_native_get_sGrey();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_12 == null)
            Color_TEMP_STATIC_GEN_12 = Color.native_new();
        Color_TEMP_STATIC_GEN_12.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_12;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sGrey;
*/
    public static native long internal_native_get_sGrey();

    public static Color get_sLightGrey() {
        long pointer = internal_native_get_sLightGrey();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_13 == null)
            Color_TEMP_STATIC_GEN_13 = Color.native_new();
        Color_TEMP_STATIC_GEN_13.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_13;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sLightGrey;
*/
    public static native long internal_native_get_sLightGrey();

    public static Color get_sWhite() {
        long pointer = internal_native_get_sWhite();
        if (pointer == 0)
            return null;
        if (Color_TEMP_STATIC_GEN_14 == null)
            Color_TEMP_STATIC_GEN_14 = Color.native_new();
        Color_TEMP_STATIC_GEN_14.internal_reset(pointer, false);
        return Color_TEMP_STATIC_GEN_14;
    }

    /*[-JNI;-NATIVE]
return (jlong)&Color::sWhite;
*/
    public static native long internal_native_get_sWhite();
}
