/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.core;

public class JobSystemThreadPool extends JobSystemWithBarrier {

    static public final JobSystemThreadPool NULL = JobSystemThreadPool.native_new();

    public JobSystemThreadPool(int inMaxJobs, int inMaxBarriers, int inNumThreads) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_int_int_int_addr(inMaxJobs, inMaxBarriers, inNumThreads);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new JobSystemThreadPool(inMaxJobs, inMaxBarriers, inNumThreads);
*/
    public static native long internal_native_create_int_int_int_addr(int inMaxJobs, int inMaxBarriers, int inNumThreads);

    public JobSystemThreadPool(int inMaxJobs, int inMaxBarriers) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_int_int_addr(inMaxJobs, inMaxBarriers);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new JobSystemThreadPool(inMaxJobs, inMaxBarriers);
*/
    public static native long internal_native_create_int_int_addr(int inMaxJobs, int inMaxBarriers);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected JobSystemThreadPool(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static JobSystemThreadPool native_new() {
        return new JobSystemThreadPool((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
JobSystemThreadPool* nativeObject = (JobSystemThreadPool*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public int GetMaxConcurrency() {
        return internal_native_GetMaxConcurrency(native_address);
    }

    /*[-JNI;-NATIVE]
JobSystemThreadPool* nativeObject = (JobSystemThreadPool*)this_addr;
return nativeObject->GetMaxConcurrency();
*/
    public static native int internal_native_GetMaxConcurrency(long this_addr);

    public void SetNumThreads(int inNumThreads) {
        internal_native_SetNumThreads(native_address, inNumThreads);
    }

    /*[-JNI;-NATIVE]
JobSystemThreadPool* nativeObject = (JobSystemThreadPool*)this_addr;
nativeObject->SetNumThreads((int)inNumThreads);
*/
    public static native void internal_native_SetNumThreads(long this_addr, int inNumThreads);
}
