/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.core;

import jolt.idl.IDLBase;

public class RefTargetShapeSettings extends IDLBase {

    static public final RefTargetShapeSettings NULL = RefTargetShapeSettings.native_new();

    static public final RefTargetShapeSettings T_01 = RefTargetShapeSettings.native_new();

    static public final RefTargetShapeSettings T_02 = RefTargetShapeSettings.native_new();

    static public final RefTargetShapeSettings T_03 = RefTargetShapeSettings.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected RefTargetShapeSettings(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static RefTargetShapeSettings native_new() {
        return new RefTargetShapeSettings((byte) 0, (char) 0);
    }

    public void SetEmbedded() {
        internal_native_SetEmbedded(native_address);
    }

    /*[-JNI;-NATIVE]
RefTargetShapeSettings* nativeObject = (RefTargetShapeSettings*)this_addr;
nativeObject->SetEmbedded();
*/
    public static native void internal_native_SetEmbedded(long this_addr);
}
