/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.core;

public class TempAllocatorImpl extends TempAllocator {

    static public final TempAllocatorImpl NULL = TempAllocatorImpl.createInstance();

    static public final TempAllocatorImpl T_01 = TempAllocatorImpl.createInstance();

    static public final TempAllocatorImpl T_02 = TempAllocatorImpl.createInstance();

    static public final TempAllocatorImpl T_03 = TempAllocatorImpl.createInstance();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected TempAllocatorImpl(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static TempAllocatorImpl createInstance() {
        return new TempAllocatorImpl((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
TempAllocatorImpl* nativeObject = (TempAllocatorImpl*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
