/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.broadphase;

import com.github.xpenatan.jParser.idl.IDLBase;

public class ObjectVsBroadPhaseLayerFilter extends IDLBase {

    static public final ObjectVsBroadPhaseLayerFilter NULL = ObjectVsBroadPhaseLayerFilter.native_new();

    public ObjectVsBroadPhaseLayerFilter() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new ObjectVsBroadPhaseLayerFilter();
*/
    public static native long internal_native_create_addr();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ObjectVsBroadPhaseLayerFilter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ObjectVsBroadPhaseLayerFilter native_new() {
        return new ObjectVsBroadPhaseLayerFilter((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
ObjectVsBroadPhaseLayerFilter* nativeObject = (ObjectVsBroadPhaseLayerFilter*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
