/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.skeleton;

import jolt.idl.IDLBase;

public class SkeletalAnimation extends IDLBase {

    private ArraySkeletonAnimatedJoint ArraySkeletonAnimatedJoint_TEMP_GEN_0;

    static public final SkeletalAnimation T_01 = new SkeletalAnimation((byte) 1, (char) 1);

    static public final SkeletalAnimation T_02 = new SkeletalAnimation((byte) 1, (char) 1);

    static public final SkeletalAnimation T_03 = new SkeletalAnimation((byte) 1, (char) 1);

    public SkeletalAnimation() {
        long addr = internal_native_create();
        internal_reset(addr, false);
    }

    /*[-JNI;-NATIVE]
return (jlong)new SkeletalAnimation();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public SkeletalAnimation(byte b, char c) {
    }

    public float GetDuration() {
        return internal_native_GetDuration(native_address);
    }

    /*[-JNI;-NATIVE]
SkeletalAnimation* nativeObject = (SkeletalAnimation*)this_addr;
return nativeObject->GetDuration();
*/
    public static native float internal_native_GetDuration(long this_addr);

    public void ScaleJoints(float inScale) {
        internal_native_ScaleJoints(native_address, inScale);
    }

    /*[-JNI;-NATIVE]
SkeletalAnimation* nativeObject = (SkeletalAnimation*)this_addr;
nativeObject->ScaleJoints((float)inScale);
*/
    public static native void internal_native_ScaleJoints(long this_addr, float inScale);

    public void Sample(float inTime, SkeletonPose ioPose) {
        internal_native_Sample(native_address, inTime, (ioPose != null ? ioPose.native_address : 0));
    }

    /*[-JNI;-NATIVE]
SkeletalAnimation* nativeObject = (SkeletalAnimation*)this_addr;
nativeObject->Sample((float)inTime, *((SkeletonPose* )ioPose_addr));
*/
    public static native void internal_native_Sample(long this_addr, float inTime, long ioPose_addr);

    public ArraySkeletonAnimatedJoint GetAnimatedJoints() {
        long pointer = internal_native_GetAnimatedJoints(native_address);
        if (pointer == 0)
            return null;
        if (ArraySkeletonAnimatedJoint_TEMP_GEN_0 == null)
            ArraySkeletonAnimatedJoint_TEMP_GEN_0 = new ArraySkeletonAnimatedJoint((byte) 1, (char) 1);
        ArraySkeletonAnimatedJoint_TEMP_GEN_0.internal_reset(pointer, false);
        return ArraySkeletonAnimatedJoint_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
SkeletalAnimation* nativeObject = (SkeletalAnimation*)this_addr;
return (jlong)&nativeObject->GetAnimatedJoints();
*/
    public static native long internal_native_GetAnimatedJoints(long this_addr);
}
