/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.body;

import jolt.idl.IDLBase;

public class ArrayBodyID extends IDLBase {

    private BodyID BodyID_TEMP_GEN_0;

    private BodyIDMemRef BodyIDMemRef_TEMP_GEN_0;

    static public final ArrayBodyID T_01 = new ArrayBodyID((byte) 1, (char) 1);

    static public final ArrayBodyID T_02 = new ArrayBodyID((byte) 1, (char) 1);

    static public final ArrayBodyID T_03 = new ArrayBodyID((byte) 1, (char) 1);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public ArrayBodyID(byte b, char c) {
    }

    public void dispose() {
        super.dispose();
    }

    public boolean isDisposed() {
        return super.isDisposed();
    }

    protected void deleteNative() {
        internal_native_deleteNative((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
ArrayBodyID* nativeObject = (ArrayBodyID*)this_addr;
delete nativeObject;
*/
    private static native void internal_native_deleteNative(long this_addr);

    public boolean empty() {
        return internal_native_empty((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
ArrayBodyID* nativeObject = (ArrayBodyID*)this_addr;
return nativeObject->empty();
*/
    private static native boolean internal_native_empty(long this_addr);

    public int size() {
        return internal_native_size((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
ArrayBodyID* nativeObject = (ArrayBodyID*)this_addr;
return nativeObject->size();
*/
    private static native int internal_native_size(long this_addr);

    public BodyID at(int inIndex) {
        long pointer = internal_native_at((long) getNativeData().getCPointer(), inIndex);
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (BodyID_TEMP_GEN_0 == null)
            BodyID_TEMP_GEN_0 = new BodyID((byte) 1, (char) 1);
        BodyID_TEMP_GEN_0.getNativeData().reset(pointer, false);
        return BodyID_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ArrayBodyID* nativeObject = (ArrayBodyID*)this_addr;
return (jlong)&nativeObject->at((int)inIndex);
*/
    private static native long internal_native_at(long this_addr, int inIndex);

    public void push_back(BodyID inValue) {
        internal_native_push_back((long) getNativeData().getCPointer(), (long) (inValue != null ? inValue.getNativeData().getCPointer() : 0));
    }

    /*[-JNI;-NATIVE]
ArrayBodyID* nativeObject = (ArrayBodyID*)this_addr;
nativeObject->push_back(*((BodyID* )inValue_addr));
*/
    private static native void internal_native_push_back(long this_addr, long inValue_addr);

    public void reserve(int inSize) {
        internal_native_reserve((long) getNativeData().getCPointer(), inSize);
    }

    /*[-JNI;-NATIVE]
ArrayBodyID* nativeObject = (ArrayBodyID*)this_addr;
nativeObject->reserve(inSize);
*/
    private static native void internal_native_reserve(long this_addr, int inSize);

    public void resize(int inSize) {
        internal_native_resize((long) getNativeData().getCPointer(), inSize);
    }

    /*[-JNI;-NATIVE]
ArrayBodyID* nativeObject = (ArrayBodyID*)this_addr;
nativeObject->resize(inSize);
*/
    private static native void internal_native_resize(long this_addr, int inSize);

    public void clear() {
        internal_native_clear((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
ArrayBodyID* nativeObject = (ArrayBodyID*)this_addr;
nativeObject->clear();
*/
    private static native void internal_native_clear(long this_addr);

    public BodyIDMemRef data() {
        long pointer = internal_native_data((long) getNativeData().getCPointer());
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (BodyIDMemRef_TEMP_GEN_0 == null)
            BodyIDMemRef_TEMP_GEN_0 = new BodyIDMemRef((byte) 1, (char) 1);
        BodyIDMemRef_TEMP_GEN_0.getNativeData().reset(pointer, false);
        return BodyIDMemRef_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ArrayBodyID* nativeObject = (ArrayBodyID*)this_addr;
BodyIDMemRef* obj = nativeObject->data();
return (jlong)obj;
*/
    private static native long internal_native_data(long this_addr);

    public static void native_deleteNative(long this_addr) {
        internal_native_deleteNative(this_addr);
    }

    public static boolean native_empty(long this_addr) {
        return internal_native_empty(this_addr);
    }

    public static int native_size(long this_addr) {
        return internal_native_size(this_addr);
    }

    public static long native_at(long this_addr, int inIndex) {
        return internal_native_at(this_addr, inIndex);
    }

    public static void native_push_back(long this_addr, long inValue_addr) {
        internal_native_push_back(this_addr, inValue_addr);
    }

    public static void native_reserve(long this_addr, int inSize) {
        internal_native_reserve(this_addr, inSize);
    }

    public static void native_resize(long this_addr, int inSize) {
        internal_native_resize(this_addr, inSize);
    }

    public static void native_clear(long this_addr) {
        internal_native_clear(this_addr);
    }

    public static long native_data(long this_addr) {
        return internal_native_data(this_addr);
    }
}
