/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.body;

import jolt.idl.IDLBase;

public class BodyIDVector extends IDLBase {

    private BodyID BodyID_TEMP_GEN_0;

    static public final BodyIDVector T_01 = new BodyIDVector((byte) 1, (char) 1);

    static public final BodyIDVector T_02 = new BodyIDVector((byte) 1, (char) 1);

    static public final BodyIDVector T_03 = new BodyIDVector((byte) 1, (char) 1);

    public BodyIDVector() {
        long addr = internal_native_create();
        getNativeData().reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new BodyIDVector();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public BodyIDVector(byte b, char c) {
    }

    public void dispose() {
        super.dispose();
    }

    public boolean isDisposed() {
        return super.isDisposed();
    }

    protected void deleteNative() {
        internal_native_deleteNative((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
BodyIDVector* nativeObject = (BodyIDVector*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public boolean empty() {
        return internal_native_empty((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
BodyIDVector* nativeObject = (BodyIDVector*)this_addr;
return nativeObject->empty();
*/
    public static native boolean internal_native_empty(long this_addr);

    public int size() {
        return internal_native_size((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
BodyIDVector* nativeObject = (BodyIDVector*)this_addr;
return nativeObject->size();
*/
    public static native int internal_native_size(long this_addr);

    public BodyID at(int inIndex) {
        long pointer = internal_native_at((long) getNativeData().getCPointer(), inIndex);
        if (pointer == 0)
            return null;
        if (BodyID_TEMP_GEN_0 == null)
            BodyID_TEMP_GEN_0 = new BodyID((byte) 1, (char) 1);
        BodyID_TEMP_GEN_0.getNativeData().reset(pointer, false);
        return BodyID_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
BodyIDVector* nativeObject = (BodyIDVector*)this_addr;
return (jlong)&nativeObject->at((int)inIndex);
*/
    public static native long internal_native_at(long this_addr, int inIndex);

    public void push_back(BodyID inBodyID) {
        internal_native_push_back((long) getNativeData().getCPointer(), (long) (inBodyID != null ? inBodyID.getNativeData().getCPointer() : 0));
    }

    /*[-JNI;-NATIVE]
BodyIDVector* nativeObject = (BodyIDVector*)this_addr;
nativeObject->push_back(*((BodyID* )inBodyID_addr));
*/
    public static native void internal_native_push_back(long this_addr, long inBodyID_addr);

    public void reserve(int inSize) {
        internal_native_reserve((long) getNativeData().getCPointer(), inSize);
    }

    /*[-JNI;-NATIVE]
BodyIDVector* nativeObject = (BodyIDVector*)this_addr;
nativeObject->reserve(inSize);
*/
    public static native void internal_native_reserve(long this_addr, int inSize);

    public void resize(int inSize) {
        internal_native_resize((long) getNativeData().getCPointer(), inSize);
    }

    /*[-JNI;-NATIVE]
BodyIDVector* nativeObject = (BodyIDVector*)this_addr;
nativeObject->resize(inSize);
*/
    public static native void internal_native_resize(long this_addr, int inSize);

    public void clear() {
        internal_native_clear((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
BodyIDVector* nativeObject = (BodyIDVector*)this_addr;
nativeObject->clear();
*/
    public static native void internal_native_clear(long this_addr);
}
