/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.enums;

import jolt.idl.IDLEnum;

public class EGroundState implements IDLEnum {

    public static final int OnGround = EGroundState_OnGround_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)EGroundState_OnGround;
*/
    private static native int EGroundState_OnGround_NATIVE();

    public static final int OnSteepGround = EGroundState_OnSteepGround_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)EGroundState_OnSteepGround;
*/
    private static native int EGroundState_OnSteepGround_NATIVE();

    public static final int NotSupported = EGroundState_NotSupported_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)EGroundState_NotSupported;
*/
    private static native int EGroundState_NotSupported_NATIVE();

    public static final int InAir = EGroundState_InAir_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)EGroundState_InAir;
*/
    private static native int EGroundState_InAir_NATIVE();
}
