/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.enums;

import jolt.idl.IDLEnum;

public class ESpringMode implements IDLEnum {

    public static final int FrequencyAndDamping = ESpringMode_FrequencyAndDamping_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ESpringMode_FrequencyAndDamping;
*/
    private static native int ESpringMode_FrequencyAndDamping_NATIVE();

    public static final int StiffnessAndDamping = ESpringMode_StiffnessAndDamping_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ESpringMode_StiffnessAndDamping;
*/
    private static native int ESpringMode_StiffnessAndDamping_NATIVE();
}
