/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.enums;

import jolt.idl.IDLEnum;

public class ESwingType implements IDLEnum {

    public static final int Cone = ESwingType_Cone_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ESwingType_Cone;
*/
    private static native int ESwingType_Cone_NATIVE();

    public static final int Pyramid = ESwingType_Pyramid_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ESwingType_Pyramid;
*/
    private static native int ESwingType_Pyramid_NATIVE();
}
