/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.enums;

import java.util.Map;
import java.util.HashMap;
import jolt.idl.IDLEnum;

public enum ETireFrictionDirection implements IDLEnum<ETireFrictionDirection> {

    CUSTOM(0), Longitudinal(ETireFrictionDirection_Longitudinal_NATIVE()), Lateral(ETireFrictionDirection_Lateral_NATIVE());

    private int value;

    private ETireFrictionDirection(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public ETireFrictionDirection getCustom() {
        return CUSTOM;
    }

    public static final Map<Integer, ETireFrictionDirection> MAP = new HashMap<>();

    static {
        for (ETireFrictionDirection value : values()) {
            if (value != CUSTOM) {
                MAP.put(value.value, value);
            }
        }
    }

    /*[-JNI;-NATIVE]
return (jlong)ETireFrictionDirection_Longitudinal;
*/
    private static native int ETireFrictionDirection_Longitudinal_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ETireFrictionDirection_Lateral;
*/
    private static native int ETireFrictionDirection_Lateral_NATIVE();
}
