/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.collision;

import jolt.idl.IDLBase;

public class ArrayCollideShapeResult extends IDLBase {

    private CollideShapeResult CollideShapeResult_TEMP_GEN_0;

    static public final ArrayCollideShapeResult NULL = ArrayCollideShapeResult.native_new();

    static public final ArrayCollideShapeResult T_01 = ArrayCollideShapeResult.native_new();

    static public final ArrayCollideShapeResult T_02 = ArrayCollideShapeResult.native_new();

    static public final ArrayCollideShapeResult T_03 = ArrayCollideShapeResult.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ArrayCollideShapeResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ArrayCollideShapeResult native_new() {
        return new ArrayCollideShapeResult((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
ArrayCollideShapeResult* nativeObject = (ArrayCollideShapeResult*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public boolean empty() {
        return internal_native_empty(native_address);
    }

    /*[-JNI;-NATIVE]
ArrayCollideShapeResult* nativeObject = (ArrayCollideShapeResult*)this_addr;
return nativeObject->empty();
*/
    public static native boolean internal_native_empty(long this_addr);

    public int size() {
        return internal_native_size(native_address);
    }

    /*[-JNI;-NATIVE]
ArrayCollideShapeResult* nativeObject = (ArrayCollideShapeResult*)this_addr;
return nativeObject->size();
*/
    public static native int internal_native_size(long this_addr);

    public CollideShapeResult at(int inIndex) {
        long pointer = internal_native_at(native_address, inIndex);
        if (pointer == 0)
            return null;
        if (CollideShapeResult_TEMP_GEN_0 == null)
            CollideShapeResult_TEMP_GEN_0 = CollideShapeResult.native_new();
        CollideShapeResult_TEMP_GEN_0.internal_reset(pointer, false);
        return CollideShapeResult_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ArrayCollideShapeResult* nativeObject = (ArrayCollideShapeResult*)this_addr;
return (jlong)&nativeObject->at((int)inIndex);
*/
    public static native long internal_native_at(long this_addr, int inIndex);

    public void push_back(CollideShapeResult inValue) {
        internal_native_push_back(native_address, inValue.native_address);
    }

    /*[-JNI;-NATIVE]
ArrayCollideShapeResult* nativeObject = (ArrayCollideShapeResult*)this_addr;
nativeObject->push_back(*((CollideShapeResult* )inValue_addr));
*/
    public static native void internal_native_push_back(long this_addr, long inValue_addr);

    public void reserve(int inSize) {
        internal_native_reserve(native_address, inSize);
    }

    /*[-JNI;-NATIVE]
ArrayCollideShapeResult* nativeObject = (ArrayCollideShapeResult*)this_addr;
nativeObject->reserve(inSize);
*/
    public static native void internal_native_reserve(long this_addr, int inSize);

    public void resize(int inSize) {
        internal_native_resize(native_address, inSize);
    }

    /*[-JNI;-NATIVE]
ArrayCollideShapeResult* nativeObject = (ArrayCollideShapeResult*)this_addr;
nativeObject->resize(inSize);
*/
    public static native void internal_native_resize(long this_addr, int inSize);

    public void clear() {
        internal_native_clear(native_address);
    }

    /*[-JNI;-NATIVE]
ArrayCollideShapeResult* nativeObject = (ArrayCollideShapeResult*)this_addr;
nativeObject->clear();
*/
    public static native void internal_native_clear(long this_addr);
}
