/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.collision;

public class ObjectLayerPairFilterMask extends ObjectLayerPairFilter {

    static public final ObjectLayerPairFilterMask T_01 = new ObjectLayerPairFilterMask((byte) 1, (char) 1);

    static public final ObjectLayerPairFilterMask T_02 = new ObjectLayerPairFilterMask((byte) 1, (char) 1);

    static public final ObjectLayerPairFilterMask T_03 = new ObjectLayerPairFilterMask((byte) 1, (char) 1);

    public ObjectLayerPairFilterMask() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        getNativeData().reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new ObjectLayerPairFilterMask();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public ObjectLayerPairFilterMask(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public void dispose() {
        super.dispose();
    }

    public boolean isDisposed() {
        return super.isDisposed();
    }

    protected void deleteNative() {
        internal_native_deleteNative((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
ObjectLayerPairFilterMask* nativeObject = (ObjectLayerPairFilterMask*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public static int sGetObjectLayer(int inGroup, int inMask) {
        return internal_native_sGetObjectLayer(inGroup, inMask);
    }

    /*[-JNI;-NATIVE]
return ObjectLayerPairFilterMask::sGetObjectLayer(inGroup, inMask);
*/
    public static native int internal_native_sGetObjectLayer(int inGroup, int inMask);

    public static int sGetGroup(int inObjectLayer) {
        return internal_native_sGetGroup(inObjectLayer);
    }

    /*[-JNI;-NATIVE]
return ObjectLayerPairFilterMask::sGetGroup(inObjectLayer);
*/
    public static native int internal_native_sGetGroup(int inObjectLayer);

    public static int sGetMask(int inObjectLayer) {
        return internal_native_sGetMask(inObjectLayer);
    }

    /*[-JNI;-NATIVE]
return ObjectLayerPairFilterMask::sGetMask(inObjectLayer);
*/
    public static native int internal_native_sGetMask(int inObjectLayer);
}
