/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.collision;

import jolt.idl.IDLBase;

public class PhysicsMaterial extends IDLBase {

    static public final PhysicsMaterial T_01 = new PhysicsMaterial((byte) 1, (char) 1);

    static public final PhysicsMaterial T_02 = new PhysicsMaterial((byte) 1, (char) 1);

    static public final PhysicsMaterial T_03 = new PhysicsMaterial((byte) 1, (char) 1);

    public PhysicsMaterial() {
        long addr = internal_native_create();
        getNativeData().reset(addr, false);
    }

    /*[-JNI;-NATIVE]
return (jlong)new PhysicsMaterial();
*/
    private static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public PhysicsMaterial(byte b, char c) {
    }

    public int GetRefCount() {
        return internal_native_GetRefCount((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
PhysicsMaterial* nativeObject = (PhysicsMaterial*)this_addr;
return nativeObject->GetRefCount();
*/
    private static native int internal_native_GetRefCount(long this_addr);

    public void AddRef() {
        internal_native_AddRef((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
PhysicsMaterial* nativeObject = (PhysicsMaterial*)this_addr;
nativeObject->AddRef();
*/
    private static native void internal_native_AddRef(long this_addr);

    public void Release() {
        internal_native_Release((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
PhysicsMaterial* nativeObject = (PhysicsMaterial*)this_addr;
nativeObject->Release();
*/
    private static native void internal_native_Release(long this_addr);

    public static long native_create() {
        return internal_native_create();
    }

    public static int native_GetRefCount(long this_addr) {
        return internal_native_GetRefCount(this_addr);
    }

    public static void native_AddRef(long this_addr) {
        internal_native_AddRef(this_addr);
    }

    public static void native_Release(long this_addr) {
        internal_native_Release(this_addr);
    }
}
