/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.collision;

import jolt.idl.IDLBase;

public class ShapeFilter extends IDLBase {

    static public final ShapeFilter NULL = ShapeFilter.native_new();

    public ShapeFilter() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new ShapeFilter();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ShapeFilter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ShapeFilter native_new() {
        return new ShapeFilter((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
ShapeFilter* nativeObject = (ShapeFilter*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
