/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.constraints;

import jolt.math.TwoBodyConstraintSettings;
import jolt.enums.EConstraintSpace;
import jolt.math.Vec3;

public class PointConstraintSettings extends TwoBodyConstraintSettings {

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    static public final PointConstraintSettings NULL = PointConstraintSettings.native_new();

    static public final PointConstraintSettings T_01 = PointConstraintSettings.native_new();

    static public final PointConstraintSettings T_02 = PointConstraintSettings.native_new();

    static public final PointConstraintSettings T_03 = PointConstraintSettings.native_new();

    public PointConstraintSettings() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new PointConstraintSettings();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected PointConstraintSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static PointConstraintSettings native_new() {
        return new PointConstraintSettings((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
PointConstraintSettings* nativeObject = (PointConstraintSettings*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public EConstraintSpace get_mSpace() {
        int value = internal_native_get_mSpace(native_address);
        return EConstraintSpace.MAP.get(value);
    }

    /*[-JNI;-NATIVE]
PointConstraintSettings* nativeObject = (PointConstraintSettings*)this_addr;
return (jint)nativeObject->mSpace;
*/
    public static native int internal_native_get_mSpace(long this_addr);

    public void set_mSpace(EConstraintSpace mSpace) {
        internal_native_set_mSpace(native_address, mSpace.getValue());
    }

    /*[-JNI;-NATIVE]
PointConstraintSettings* nativeObject = (PointConstraintSettings*)this_addr;
nativeObject->mSpace = (::EConstraintSpace)mSpace;
*/
    public static native void internal_native_set_mSpace(long this_addr, long mSpace);

    public Vec3 get_mPoint1() {
        long pointer = internal_native_get_mPoint1(native_address);
        if (pointer == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
PointConstraintSettings* nativeObject = (PointConstraintSettings*)this_addr;
return (jlong)&nativeObject->mPoint1;
*/
    public static native long internal_native_get_mPoint1(long this_addr);

    public void set_mPoint1(Vec3 mPoint1) {
        internal_native_set_mPoint1(native_address, mPoint1.native_address);
    }

    /*[-JNI;-NATIVE]
PointConstraintSettings* nativeObject = (PointConstraintSettings*)this_addr;
nativeObject->mPoint1 = *((Vec3*)mPoint1_addr);
*/
    public static native void internal_native_set_mPoint1(long this_addr, long mPoint1_addr);

    public Vec3 get_mPoint2() {
        long pointer = internal_native_get_mPoint2(native_address);
        if (pointer == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = Vec3.native_new();
        Vec3_TEMP_GEN_1.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_1;
    }

    /*[-JNI;-NATIVE]
PointConstraintSettings* nativeObject = (PointConstraintSettings*)this_addr;
return (jlong)&nativeObject->mPoint2;
*/
    public static native long internal_native_get_mPoint2(long this_addr);

    public void set_mPoint2(Vec3 mPoint2) {
        internal_native_set_mPoint2(native_address, mPoint2.native_address);
    }

    /*[-JNI;-NATIVE]
PointConstraintSettings* nativeObject = (PointConstraintSettings*)this_addr;
nativeObject->mPoint2 = *((Vec3*)mPoint2_addr);
*/
    public static native void internal_native_set_mPoint2(long this_addr, long mPoint2_addr);
}
