/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.constraints;

import jolt.math.Vec3;
import jolt.math.Quat;
import jolt.enums.EMotorState;

public class SwingTwistConstraint extends TwoBodyConstraint {

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    private Quat Quat_TEMP_GEN_0;

    private Quat Quat_TEMP_GEN_1;

    private MotorSettings MotorSettings_TEMP_GEN_0;

    private MotorSettings MotorSettings_TEMP_GEN_1;

    private Vec3 Vec3_TEMP_GEN_2;

    private Quat Quat_TEMP_GEN_2;

    private Quat Quat_TEMP_GEN_3;

    private Vec3 Vec3_TEMP_GEN_3;

    private Vec3 Vec3_TEMP_GEN_4;

    static public final SwingTwistConstraint T_01 = new SwingTwistConstraint((byte) 1, (char) 1);

    static public final SwingTwistConstraint T_02 = new SwingTwistConstraint((byte) 1, (char) 1);

    static public final SwingTwistConstraint T_03 = new SwingTwistConstraint((byte) 1, (char) 1);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public SwingTwistConstraint(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public Vec3 GetLocalSpacePosition1() {
        long pointer = internal_native_GetLocalSpacePosition1(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_0.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
static Vec3 copy_addr;
copy_addr = nativeObject->GetLocalSpacePosition1();
return (jlong)&copy_addr;*/
    public static native long internal_native_GetLocalSpacePosition1(long this_addr);

    public Vec3 GetLocalSpacePosition2() {
        long pointer = internal_native_GetLocalSpacePosition2(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_1.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_1;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
static Vec3 copy_addr;
copy_addr = nativeObject->GetLocalSpacePosition2();
return (jlong)&copy_addr;*/
    public static native long internal_native_GetLocalSpacePosition2(long this_addr);

    public Quat GetConstraintToBody1() {
        long pointer = internal_native_GetConstraintToBody1(native_address);
        if (pointer == 0)
            return null;
        if (Quat_TEMP_GEN_0 == null)
            Quat_TEMP_GEN_0 = new Quat((byte) 1, (char) 1);
        Quat_TEMP_GEN_0.internal_reset(pointer, false);
        return Quat_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
static Quat copy_addr;
copy_addr = nativeObject->GetConstraintToBody1();
return (jlong)&copy_addr;*/
    public static native long internal_native_GetConstraintToBody1(long this_addr);

    public Quat GetConstraintToBody2() {
        long pointer = internal_native_GetConstraintToBody2(native_address);
        if (pointer == 0)
            return null;
        if (Quat_TEMP_GEN_1 == null)
            Quat_TEMP_GEN_1 = new Quat((byte) 1, (char) 1);
        Quat_TEMP_GEN_1.internal_reset(pointer, false);
        return Quat_TEMP_GEN_1;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
static Quat copy_addr;
copy_addr = nativeObject->GetConstraintToBody2();
return (jlong)&copy_addr;*/
    public static native long internal_native_GetConstraintToBody2(long this_addr);

    public float GetNormalHalfConeAngle() {
        return internal_native_GetNormalHalfConeAngle(native_address);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return nativeObject->GetNormalHalfConeAngle();
*/
    public static native float internal_native_GetNormalHalfConeAngle(long this_addr);

    public void SetNormalHalfConeAngle(float inAngle) {
        internal_native_SetNormalHalfConeAngle(native_address, inAngle);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
nativeObject->SetNormalHalfConeAngle((float)inAngle);
*/
    public static native void internal_native_SetNormalHalfConeAngle(long this_addr, float inAngle);

    public float GetPlaneHalfConeAngle() {
        return internal_native_GetPlaneHalfConeAngle(native_address);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return nativeObject->GetPlaneHalfConeAngle();
*/
    public static native float internal_native_GetPlaneHalfConeAngle(long this_addr);

    public void SetPlaneHalfConeAngle(float inAngle) {
        internal_native_SetPlaneHalfConeAngle(native_address, inAngle);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
nativeObject->SetPlaneHalfConeAngle((float)inAngle);
*/
    public static native void internal_native_SetPlaneHalfConeAngle(long this_addr, float inAngle);

    public float GetTwistMinAngle() {
        return internal_native_GetTwistMinAngle(native_address);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return nativeObject->GetTwistMinAngle();
*/
    public static native float internal_native_GetTwistMinAngle(long this_addr);

    public void SetTwistMinAngle(float inAngle) {
        internal_native_SetTwistMinAngle(native_address, inAngle);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
nativeObject->SetTwistMinAngle((float)inAngle);
*/
    public static native void internal_native_SetTwistMinAngle(long this_addr, float inAngle);

    public float GetTwistMaxAngle() {
        return internal_native_GetTwistMaxAngle(native_address);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return nativeObject->GetTwistMaxAngle();
*/
    public static native float internal_native_GetTwistMaxAngle(long this_addr);

    public void SetTwistMaxAngle(float inAngle) {
        internal_native_SetTwistMaxAngle(native_address, inAngle);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
nativeObject->SetTwistMaxAngle((float)inAngle);
*/
    public static native void internal_native_SetTwistMaxAngle(long this_addr, float inAngle);

    public MotorSettings GetSwingMotorSettings() {
        long pointer = internal_native_GetSwingMotorSettings(native_address);
        if (pointer == 0)
            return null;
        if (MotorSettings_TEMP_GEN_0 == null)
            MotorSettings_TEMP_GEN_0 = new MotorSettings((byte) 1, (char) 1);
        MotorSettings_TEMP_GEN_0.internal_reset(pointer, false);
        return MotorSettings_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return (jlong)&nativeObject->GetSwingMotorSettings();
*/
    public static native long internal_native_GetSwingMotorSettings(long this_addr);

    public MotorSettings GetTwistMotorSettings() {
        long pointer = internal_native_GetTwistMotorSettings(native_address);
        if (pointer == 0)
            return null;
        if (MotorSettings_TEMP_GEN_1 == null)
            MotorSettings_TEMP_GEN_1 = new MotorSettings((byte) 1, (char) 1);
        MotorSettings_TEMP_GEN_1.internal_reset(pointer, false);
        return MotorSettings_TEMP_GEN_1;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return (jlong)&nativeObject->GetTwistMotorSettings();
*/
    public static native long internal_native_GetTwistMotorSettings(long this_addr);

    public void SetMaxFrictionTorque(float inFrictionTorque) {
        internal_native_SetMaxFrictionTorque(native_address, inFrictionTorque);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
nativeObject->SetMaxFrictionTorque((float)inFrictionTorque);
*/
    public static native void internal_native_SetMaxFrictionTorque(long this_addr, float inFrictionTorque);

    public float GetMaxFrictionTorque() {
        return internal_native_GetMaxFrictionTorque(native_address);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return nativeObject->GetMaxFrictionTorque();
*/
    public static native float internal_native_GetMaxFrictionTorque(long this_addr);

    public void SetSwingMotorState(EMotorState inState) {
        internal_native_SetSwingMotorState(native_address, (inState != null ? inState.getValue() : 0));
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
nativeObject->SetSwingMotorState((::EMotorState)inState);
*/
    public static native void internal_native_SetSwingMotorState(long this_addr, long inState);

    public EMotorState GetSwingMotorState() {
        int value = internal_native_GetSwingMotorState(native_address);
        return EMotorState.MAP.get(value);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return (int)nativeObject->GetSwingMotorState();
*/
    public static native int internal_native_GetSwingMotorState(long this_addr);

    public void SetTwistMotorState(EMotorState inState) {
        internal_native_SetTwistMotorState(native_address, (inState != null ? inState.getValue() : 0));
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
nativeObject->SetTwistMotorState((::EMotorState)inState);
*/
    public static native void internal_native_SetTwistMotorState(long this_addr, long inState);

    public EMotorState GetTwistMotorState() {
        int value = internal_native_GetTwistMotorState(native_address);
        return EMotorState.MAP.get(value);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return (int)nativeObject->GetTwistMotorState();
*/
    public static native int internal_native_GetTwistMotorState(long this_addr);

    public void SetTargetAngularVelocityCS(Vec3 inAngularVelocity) {
        internal_native_SetTargetAngularVelocityCS(native_address, (inAngularVelocity != null ? inAngularVelocity.native_address : 0));
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
nativeObject->SetTargetAngularVelocityCS(*((Vec3* )inAngularVelocity_addr));
*/
    public static native void internal_native_SetTargetAngularVelocityCS(long this_addr, long inAngularVelocity_addr);

    public Vec3 GetTargetAngularVelocityCS() {
        long pointer = internal_native_GetTargetAngularVelocityCS(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_2 == null)
            Vec3_TEMP_GEN_2 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_2.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_2;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
static Vec3 copy_addr;
copy_addr = nativeObject->GetTargetAngularVelocityCS();
return (jlong)&copy_addr;*/
    public static native long internal_native_GetTargetAngularVelocityCS(long this_addr);

    public void SetTargetOrientationCS(Quat inOrientation) {
        internal_native_SetTargetOrientationCS(native_address, (inOrientation != null ? inOrientation.native_address : 0));
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
nativeObject->SetTargetOrientationCS(*((Quat* )inOrientation_addr));
*/
    public static native void internal_native_SetTargetOrientationCS(long this_addr, long inOrientation_addr);

    public Quat GetTargetOrientationCS() {
        long pointer = internal_native_GetTargetOrientationCS(native_address);
        if (pointer == 0)
            return null;
        if (Quat_TEMP_GEN_2 == null)
            Quat_TEMP_GEN_2 = new Quat((byte) 1, (char) 1);
        Quat_TEMP_GEN_2.internal_reset(pointer, false);
        return Quat_TEMP_GEN_2;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
static Quat copy_addr;
copy_addr = nativeObject->GetTargetOrientationCS();
return (jlong)&copy_addr;*/
    public static native long internal_native_GetTargetOrientationCS(long this_addr);

    public void SetTargetOrientationBS(Quat inOrientation) {
        internal_native_SetTargetOrientationBS(native_address, (inOrientation != null ? inOrientation.native_address : 0));
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
nativeObject->SetTargetOrientationBS(*((Quat* )inOrientation_addr));
*/
    public static native void internal_native_SetTargetOrientationBS(long this_addr, long inOrientation_addr);

    public Quat GetRotationInConstraintSpace() {
        long pointer = internal_native_GetRotationInConstraintSpace(native_address);
        if (pointer == 0)
            return null;
        if (Quat_TEMP_GEN_3 == null)
            Quat_TEMP_GEN_3 = new Quat((byte) 1, (char) 1);
        Quat_TEMP_GEN_3.internal_reset(pointer, false);
        return Quat_TEMP_GEN_3;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
static Quat copy_addr;
copy_addr = nativeObject->GetRotationInConstraintSpace();
return (jlong)&copy_addr;*/
    public static native long internal_native_GetRotationInConstraintSpace(long this_addr);

    public Vec3 GetTotalLambdaPosition() {
        long pointer = internal_native_GetTotalLambdaPosition(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_3 == null)
            Vec3_TEMP_GEN_3 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_3.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_3;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
static Vec3 copy_addr;
copy_addr = nativeObject->GetTotalLambdaPosition();
return (jlong)&copy_addr;*/
    public static native long internal_native_GetTotalLambdaPosition(long this_addr);

    public float GetTotalLambdaTwist() {
        return internal_native_GetTotalLambdaTwist(native_address);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return nativeObject->GetTotalLambdaTwist();
*/
    public static native float internal_native_GetTotalLambdaTwist(long this_addr);

    public float GetTotalLambdaSwingY() {
        return internal_native_GetTotalLambdaSwingY(native_address);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return nativeObject->GetTotalLambdaSwingY();
*/
    public static native float internal_native_GetTotalLambdaSwingY(long this_addr);

    public float GetTotalLambdaSwingZ() {
        return internal_native_GetTotalLambdaSwingZ(native_address);
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
return nativeObject->GetTotalLambdaSwingZ();
*/
    public static native float internal_native_GetTotalLambdaSwingZ(long this_addr);

    public Vec3 GetTotalLambdaMotor() {
        long pointer = internal_native_GetTotalLambdaMotor(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_4 == null)
            Vec3_TEMP_GEN_4 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_4.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_4;
    }

    /*[-JNI;-NATIVE]
SwingTwistConstraint* nativeObject = (SwingTwistConstraint*)this_addr;
static Vec3 copy_addr;
copy_addr = nativeObject->GetTotalLambdaMotor();
return (jlong)&copy_addr;*/
    public static native long internal_native_GetTotalLambdaMotor(long this_addr);
}
