/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.character;

import jolt.idl.IDLBase;
import jolt.math.Vec3;
import jolt.physics.body.BodyID;
import jolt.physics.collision.shape.SubShapeID;
import jolt.enums.EMotionType;
import jolt.physics.collision.PhysicsMaterial;

public class CharacterVirtualContact extends IDLBase {

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    private Vec3 Vec3_TEMP_GEN_2;

    private Vec3 Vec3_TEMP_GEN_3;

    private BodyID BodyID_TEMP_GEN_0;

    private CharacterID CharacterID_TEMP_GEN_0;

    private SubShapeID SubShapeID_TEMP_GEN_0;

    private CharacterVirtual CharacterVirtual_TEMP_GEN_0;

    private PhysicsMaterial PhysicsMaterial_TEMP_GEN_0;

    static public final CharacterVirtualContact NULL = CharacterVirtualContact.createInstance();

    static public final CharacterVirtualContact T_01 = CharacterVirtualContact.createInstance();

    static public final CharacterVirtualContact T_02 = CharacterVirtualContact.createInstance();

    static public final CharacterVirtualContact T_03 = CharacterVirtualContact.createInstance();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CharacterVirtualContact(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static CharacterVirtualContact createInstance() {
        return new CharacterVirtualContact((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public boolean IsSameBody(CharacterVirtualContact inOther) {
        return internal_native_IsSameBody(native_address, inOther.native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return nativeObject->IsSameBody(*((CharacterVirtualContact* )inOther_addr));
*/
    public static native boolean internal_native_IsSameBody(long this_addr, long inOther_addr);

    public Vec3 get_mPosition() {
        long pointer = internal_native_get_mPosition(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.createInstance();
        Vec3_TEMP_GEN_0.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return (jlong)&nativeObject->mPosition;
*/
    public static native long internal_native_get_mPosition(long this_addr);

    public void set_mPosition(Vec3 mPosition) {
        internal_native_set_mPosition(native_address, mPosition.native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mPosition = *((Vec3*)mPosition_addr);
*/
    public static native void internal_native_set_mPosition(long this_addr, long mPosition_addr);

    public Vec3 get_mLinearVelocity() {
        long pointer = internal_native_get_mLinearVelocity(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = Vec3.createInstance();
        Vec3_TEMP_GEN_1.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_1;
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return (jlong)&nativeObject->mLinearVelocity;
*/
    public static native long internal_native_get_mLinearVelocity(long this_addr);

    public void set_mLinearVelocity(Vec3 mLinearVelocity) {
        internal_native_set_mLinearVelocity(native_address, mLinearVelocity.native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mLinearVelocity = *((Vec3*)mLinearVelocity_addr);
*/
    public static native void internal_native_set_mLinearVelocity(long this_addr, long mLinearVelocity_addr);

    public Vec3 get_mContactNormal() {
        long pointer = internal_native_get_mContactNormal(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_2 == null)
            Vec3_TEMP_GEN_2 = Vec3.createInstance();
        Vec3_TEMP_GEN_2.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_2;
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return (jlong)&nativeObject->mContactNormal;
*/
    public static native long internal_native_get_mContactNormal(long this_addr);

    public void set_mContactNormal(Vec3 mContactNormal) {
        internal_native_set_mContactNormal(native_address, mContactNormal.native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mContactNormal = *((Vec3*)mContactNormal_addr);
*/
    public static native void internal_native_set_mContactNormal(long this_addr, long mContactNormal_addr);

    public Vec3 get_mSurfaceNormal() {
        long pointer = internal_native_get_mSurfaceNormal(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_3 == null)
            Vec3_TEMP_GEN_3 = Vec3.createInstance();
        Vec3_TEMP_GEN_3.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_3;
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return (jlong)&nativeObject->mSurfaceNormal;
*/
    public static native long internal_native_get_mSurfaceNormal(long this_addr);

    public void set_mSurfaceNormal(Vec3 mSurfaceNormal) {
        internal_native_set_mSurfaceNormal(native_address, mSurfaceNormal.native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mSurfaceNormal = *((Vec3*)mSurfaceNormal_addr);
*/
    public static native void internal_native_set_mSurfaceNormal(long this_addr, long mSurfaceNormal_addr);

    public float get_mDistance() {
        return internal_native_get_mDistance(native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return nativeObject->mDistance;
*/
    public static native float internal_native_get_mDistance(long this_addr);

    public void set_mDistance(float mDistance) {
        internal_native_set_mDistance(native_address, mDistance);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mDistance = mDistance;
*/
    public static native void internal_native_set_mDistance(long this_addr, float mDistance);

    public float get_mFraction() {
        return internal_native_get_mFraction(native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return nativeObject->mFraction;
*/
    public static native float internal_native_get_mFraction(long this_addr);

    public void set_mFraction(float mFraction) {
        internal_native_set_mFraction(native_address, mFraction);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mFraction = mFraction;
*/
    public static native void internal_native_set_mFraction(long this_addr, float mFraction);

    public BodyID get_mBodyB() {
        long pointer = internal_native_get_mBodyB(native_address);
        if (pointer == 0)
            return null;
        if (BodyID_TEMP_GEN_0 == null)
            BodyID_TEMP_GEN_0 = BodyID.createInstance();
        BodyID_TEMP_GEN_0.internal_reset(pointer, false);
        return BodyID_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return (jlong)&nativeObject->mBodyB;
*/
    public static native long internal_native_get_mBodyB(long this_addr);

    public void set_mBodyB(BodyID mBodyB) {
        internal_native_set_mBodyB(native_address, mBodyB.native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mBodyB = *((BodyID*)mBodyB_addr);
*/
    public static native void internal_native_set_mBodyB(long this_addr, long mBodyB_addr);

    public CharacterID get_mCharacterIDB() {
        long pointer = internal_native_get_mCharacterIDB(native_address);
        if (pointer == 0)
            return null;
        if (CharacterID_TEMP_GEN_0 == null)
            CharacterID_TEMP_GEN_0 = CharacterID.createInstance();
        CharacterID_TEMP_GEN_0.internal_reset(pointer, false);
        return CharacterID_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return (jlong)&nativeObject->mCharacterIDB;
*/
    public static native long internal_native_get_mCharacterIDB(long this_addr);

    public void set_mCharacterIDB(CharacterID mCharacterIDB) {
        internal_native_set_mCharacterIDB(native_address, mCharacterIDB.native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mCharacterIDB = *((CharacterID*)mCharacterIDB_addr);
*/
    public static native void internal_native_set_mCharacterIDB(long this_addr, long mCharacterIDB_addr);

    public SubShapeID get_mSubShapeIDB() {
        long pointer = internal_native_get_mSubShapeIDB(native_address);
        if (pointer == 0)
            return null;
        if (SubShapeID_TEMP_GEN_0 == null)
            SubShapeID_TEMP_GEN_0 = SubShapeID.createInstance();
        SubShapeID_TEMP_GEN_0.internal_reset(pointer, false);
        return SubShapeID_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return (jlong)&nativeObject->mSubShapeIDB;
*/
    public static native long internal_native_get_mSubShapeIDB(long this_addr);

    public void set_mSubShapeIDB(SubShapeID mSubShapeIDB) {
        internal_native_set_mSubShapeIDB(native_address, mSubShapeIDB.native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mSubShapeIDB = *((SubShapeID*)mSubShapeIDB_addr);
*/
    public static native void internal_native_set_mSubShapeIDB(long this_addr, long mSubShapeIDB_addr);

    public EMotionType get_mMotionTypeB() {
        int value = internal_native_get_mMotionTypeB(native_address);
        return EMotionType.MAP.get(value);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return (jint)nativeObject->mMotionTypeB;
*/
    public static native int internal_native_get_mMotionTypeB(long this_addr);

    public void set_mMotionTypeB(EMotionType mMotionTypeB) {
        internal_native_set_mMotionTypeB(native_address, mMotionTypeB.getValue());
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mMotionTypeB = (::EMotionType)mMotionTypeB;
*/
    public static native void internal_native_set_mMotionTypeB(long this_addr, long mMotionTypeB);

    public boolean get_mIsSensorB() {
        return internal_native_get_mIsSensorB(native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return nativeObject->mIsSensorB;
*/
    public static native boolean internal_native_get_mIsSensorB(long this_addr);

    public void set_mIsSensorB(boolean mIsSensorB) {
        internal_native_set_mIsSensorB(native_address, mIsSensorB);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mIsSensorB = mIsSensorB;
*/
    public static native void internal_native_set_mIsSensorB(long this_addr, boolean mIsSensorB);

    public CharacterVirtual get_mCharacterB() {
        long pointer = internal_native_get_mCharacterB(native_address);
        if (pointer == 0)
            return null;
        if (CharacterVirtual_TEMP_GEN_0 == null)
            CharacterVirtual_TEMP_GEN_0 = CharacterVirtual.createInstance();
        CharacterVirtual_TEMP_GEN_0.internal_reset(pointer, false);
        return CharacterVirtual_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
const CharacterVirtual* attr = nativeObject->mCharacterB;
return (jlong)attr;
*/
    public static native long internal_native_get_mCharacterB(long this_addr);

    public void set_mCharacterB(CharacterVirtual mCharacterB) {
        internal_native_set_mCharacterB(native_address, mCharacterB.native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mCharacterB = (CharacterVirtual*)mCharacterB_addr;
*/
    public static native void internal_native_set_mCharacterB(long this_addr, long mCharacterB_addr);

    public long get_mUserData() {
        return internal_native_get_mUserData(native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return nativeObject->mUserData;
*/
    public static native long internal_native_get_mUserData(long this_addr);

    public void set_mUserData(long mUserData) {
        internal_native_set_mUserData(native_address, mUserData);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mUserData = mUserData;
*/
    public static native void internal_native_set_mUserData(long this_addr, long mUserData);

    public PhysicsMaterial get_mMaterial() {
        long pointer = internal_native_get_mMaterial(native_address);
        if (pointer == 0)
            return null;
        if (PhysicsMaterial_TEMP_GEN_0 == null)
            PhysicsMaterial_TEMP_GEN_0 = PhysicsMaterial.createInstance();
        PhysicsMaterial_TEMP_GEN_0.internal_reset(pointer, false);
        return PhysicsMaterial_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
const PhysicsMaterial* attr = nativeObject->mMaterial;
return (jlong)attr;
*/
    public static native long internal_native_get_mMaterial(long this_addr);

    public void set_mMaterial(PhysicsMaterial mMaterial) {
        internal_native_set_mMaterial(native_address, mMaterial.native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mMaterial = (PhysicsMaterial*)mMaterial_addr;
*/
    public static native void internal_native_set_mMaterial(long this_addr, long mMaterial_addr);

    public boolean get_mHadCollision() {
        return internal_native_get_mHadCollision(native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return nativeObject->mHadCollision;
*/
    public static native boolean internal_native_get_mHadCollision(long this_addr);

    public void set_mHadCollision(boolean mHadCollision) {
        internal_native_set_mHadCollision(native_address, mHadCollision);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mHadCollision = mHadCollision;
*/
    public static native void internal_native_set_mHadCollision(long this_addr, boolean mHadCollision);

    public boolean get_mWasDiscarded() {
        return internal_native_get_mWasDiscarded(native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return nativeObject->mWasDiscarded;
*/
    public static native boolean internal_native_get_mWasDiscarded(long this_addr);

    public void set_mWasDiscarded(boolean mWasDiscarded) {
        internal_native_set_mWasDiscarded(native_address, mWasDiscarded);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mWasDiscarded = mWasDiscarded;
*/
    public static native void internal_native_set_mWasDiscarded(long this_addr, boolean mWasDiscarded);

    public boolean get_mCanPushCharacter() {
        return internal_native_get_mCanPushCharacter(native_address);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
return nativeObject->mCanPushCharacter;
*/
    public static native boolean internal_native_get_mCanPushCharacter(long this_addr);

    public void set_mCanPushCharacter(boolean mCanPushCharacter) {
        internal_native_set_mCanPushCharacter(native_address, mCanPushCharacter);
    }

    /*[-JNI;-NATIVE]
CharacterVirtualContact* nativeObject = (CharacterVirtualContact*)this_addr;
nativeObject->mCanPushCharacter = mCanPushCharacter;
*/
    public static native void internal_native_set_mCanPushCharacter(long this_addr, boolean mCanPushCharacter);
}
