/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.character;

import jolt.idl.IDLBase;
import jolt.math.Vec3;

public class ExtendedUpdateSettings extends IDLBase {

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    private Vec3 Vec3_TEMP_GEN_2;

    static public final ExtendedUpdateSettings T_01 = new ExtendedUpdateSettings((byte) 1, (char) 1);

    static public final ExtendedUpdateSettings T_02 = new ExtendedUpdateSettings((byte) 1, (char) 1);

    static public final ExtendedUpdateSettings T_03 = new ExtendedUpdateSettings((byte) 1, (char) 1);

    public ExtendedUpdateSettings() {
        long addr = internal_native_create();
        getNativeData().reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new CharacterVirtual::ExtendedUpdateSettings();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public ExtendedUpdateSettings(byte b, char c) {
    }

    public void dispose() {
        super.dispose();
    }

    public boolean isDisposed() {
        return super.isDisposed();
    }

    protected void deleteNative() {
        internal_native_deleteNative((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public Vec3 get_mStickToFloorStepDown() {
        long pointer = internal_native_get_mStickToFloorStepDown((long) getNativeData().getCPointer());
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_0.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
return (jlong)&nativeObject->mStickToFloorStepDown;
*/
    public static native long internal_native_get_mStickToFloorStepDown(long this_addr);

    public void set_mStickToFloorStepDown(Vec3 mStickToFloorStepDown) {
        internal_native_set_mStickToFloorStepDown((long) getNativeData().getCPointer(), (long) (mStickToFloorStepDown != null ? mStickToFloorStepDown.getNativeData().getCPointer() : 0));
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
nativeObject->mStickToFloorStepDown = *((Vec3*)mStickToFloorStepDown_addr);
*/
    public static native void internal_native_set_mStickToFloorStepDown(long this_addr, long mStickToFloorStepDown_addr);

    public Vec3 get_mWalkStairsStepUp() {
        long pointer = internal_native_get_mWalkStairsStepUp((long) getNativeData().getCPointer());
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_1.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_1;
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
return (jlong)&nativeObject->mWalkStairsStepUp;
*/
    public static native long internal_native_get_mWalkStairsStepUp(long this_addr);

    public void set_mWalkStairsStepUp(Vec3 mWalkStairsStepUp) {
        internal_native_set_mWalkStairsStepUp((long) getNativeData().getCPointer(), (long) (mWalkStairsStepUp != null ? mWalkStairsStepUp.getNativeData().getCPointer() : 0));
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
nativeObject->mWalkStairsStepUp = *((Vec3*)mWalkStairsStepUp_addr);
*/
    public static native void internal_native_set_mWalkStairsStepUp(long this_addr, long mWalkStairsStepUp_addr);

    public float get_mWalkStairsMinStepForward() {
        return internal_native_get_mWalkStairsMinStepForward((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
return nativeObject->mWalkStairsMinStepForward;
*/
    public static native float internal_native_get_mWalkStairsMinStepForward(long this_addr);

    public void set_mWalkStairsMinStepForward(float mWalkStairsMinStepForward) {
        internal_native_set_mWalkStairsMinStepForward((long) getNativeData().getCPointer(), mWalkStairsMinStepForward);
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
nativeObject->mWalkStairsMinStepForward = mWalkStairsMinStepForward;
*/
    public static native void internal_native_set_mWalkStairsMinStepForward(long this_addr, float mWalkStairsMinStepForward);

    public float get_mWalkStairsStepForwardTest() {
        return internal_native_get_mWalkStairsStepForwardTest((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
return nativeObject->mWalkStairsStepForwardTest;
*/
    public static native float internal_native_get_mWalkStairsStepForwardTest(long this_addr);

    public void set_mWalkStairsStepForwardTest(float mWalkStairsStepForwardTest) {
        internal_native_set_mWalkStairsStepForwardTest((long) getNativeData().getCPointer(), mWalkStairsStepForwardTest);
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
nativeObject->mWalkStairsStepForwardTest = mWalkStairsStepForwardTest;
*/
    public static native void internal_native_set_mWalkStairsStepForwardTest(long this_addr, float mWalkStairsStepForwardTest);

    public float get_mWalkStairsCosAngleForwardContact() {
        return internal_native_get_mWalkStairsCosAngleForwardContact((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
return nativeObject->mWalkStairsCosAngleForwardContact;
*/
    public static native float internal_native_get_mWalkStairsCosAngleForwardContact(long this_addr);

    public void set_mWalkStairsCosAngleForwardContact(float mWalkStairsCosAngleForwardContact) {
        internal_native_set_mWalkStairsCosAngleForwardContact((long) getNativeData().getCPointer(), mWalkStairsCosAngleForwardContact);
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
nativeObject->mWalkStairsCosAngleForwardContact = mWalkStairsCosAngleForwardContact;
*/
    public static native void internal_native_set_mWalkStairsCosAngleForwardContact(long this_addr, float mWalkStairsCosAngleForwardContact);

    public Vec3 get_mWalkStairsStepDownExtra() {
        long pointer = internal_native_get_mWalkStairsStepDownExtra((long) getNativeData().getCPointer());
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_2 == null)
            Vec3_TEMP_GEN_2 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_2.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_2;
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
return (jlong)&nativeObject->mWalkStairsStepDownExtra;
*/
    public static native long internal_native_get_mWalkStairsStepDownExtra(long this_addr);

    public void set_mWalkStairsStepDownExtra(Vec3 mWalkStairsStepDownExtra) {
        internal_native_set_mWalkStairsStepDownExtra((long) getNativeData().getCPointer(), (long) (mWalkStairsStepDownExtra != null ? mWalkStairsStepDownExtra.getNativeData().getCPointer() : 0));
    }

    /*[-JNI;-NATIVE]
CharacterVirtual::ExtendedUpdateSettings* nativeObject = (CharacterVirtual::ExtendedUpdateSettings*)this_addr;
nativeObject->mWalkStairsStepDownExtra = *((Vec3*)mWalkStairsStepDownExtra_addr);
*/
    public static native void internal_native_set_mWalkStairsStepDownExtra(long this_addr, long mWalkStairsStepDownExtra_addr);
}
