/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.softbody;

import jolt.idl.IDLBase;

public class SoftBodySharedSettingsLRA extends IDLBase {

    static public final SoftBodySharedSettingsLRA T_01 = new SoftBodySharedSettingsLRA((byte) 1, (char) 1);

    static public final SoftBodySharedSettingsLRA T_02 = new SoftBodySharedSettingsLRA((byte) 1, (char) 1);

    static public final SoftBodySharedSettingsLRA T_03 = new SoftBodySharedSettingsLRA((byte) 1, (char) 1);

    public SoftBodySharedSettingsLRA(int inVertex1, int inVertex2, float inMaxDistance) {
        long addr = internal_native_create_int_int_float(inVertex1, inVertex2, inMaxDistance);
        getNativeData().reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new SoftBodySharedSettingsLRA(inVertex1, inVertex2, (float)inMaxDistance);
*/
    private static native long internal_native_create_int_int_float(int inVertex1, int inVertex2, float inMaxDistance);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public SoftBodySharedSettingsLRA(byte b, char c) {
    }

    public void dispose() {
        super.dispose();
    }

    public boolean isDisposed() {
        return super.isDisposed();
    }

    protected void deleteNative() {
        internal_native_deleteNative((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
SoftBodySharedSettingsLRA* nativeObject = (SoftBodySharedSettingsLRA*)this_addr;
delete nativeObject;
*/
    private static native void internal_native_deleteNative(long this_addr);

    public int get_mVertex(int index) {
        return internal_native_get_mVertex((long) getNativeData().getCPointer(), index);
    }

    /*[-JNI;-NATIVE]
SoftBodySharedSettingsLRA* nativeObject = (SoftBodySharedSettingsLRA*)this_addr;
return nativeObject->mVertex[index];
*/
    private static native int internal_native_get_mVertex(long this_addr, int index);

    public void set_mVertex(int index, int mVertex) {
        internal_native_set_mVertex((long) getNativeData().getCPointer(), index, mVertex);
    }

    /*[-JNI;-NATIVE]
SoftBodySharedSettingsLRA* nativeObject = (SoftBodySharedSettingsLRA*)this_addr;
nativeObject->mVertex[index] = mVertex;
*/
    private static native void internal_native_set_mVertex(long this_addr, int index, int mVertex);

    public float get_mMaxDistance() {
        return internal_native_get_mMaxDistance((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
SoftBodySharedSettingsLRA* nativeObject = (SoftBodySharedSettingsLRA*)this_addr;
return nativeObject->mMaxDistance;
*/
    private static native float internal_native_get_mMaxDistance(long this_addr);

    public void set_mMaxDistance(float mMaxDistance) {
        internal_native_set_mMaxDistance((long) getNativeData().getCPointer(), mMaxDistance);
    }

    /*[-JNI;-NATIVE]
SoftBodySharedSettingsLRA* nativeObject = (SoftBodySharedSettingsLRA*)this_addr;
nativeObject->mMaxDistance = mMaxDistance;
*/
    private static native void internal_native_set_mMaxDistance(long this_addr, float mMaxDistance);

    public static long native_create_int_int_float(int inVertex1, int inVertex2, float inMaxDistance) {
        return internal_native_create_int_int_float(inVertex1, inVertex2, inMaxDistance);
    }

    public static void native_deleteNative(long this_addr) {
        internal_native_deleteNative(this_addr);
    }

    public static int native_get_mVertex(long this_addr, int index) {
        return internal_native_get_mVertex(this_addr, index);
    }

    public static void native_set_mVertex(long this_addr, int index, int mVertex) {
        internal_native_set_mVertex(this_addr, index, mVertex);
    }

    public static float native_get_mMaxDistance(long this_addr) {
        return internal_native_get_mMaxDistance(this_addr);
    }

    public static void native_set_mMaxDistance(long this_addr, float mMaxDistance) {
        internal_native_set_mMaxDistance(this_addr, mMaxDistance);
    }
}
