/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.softbody;

import jolt.idl.IDLBase;
import jolt.physics.collision.TransformedShape;
import jolt.physics.body.Body;

public class TransformedShapeCollector extends IDLBase {

    private TransformedShape TransformedShape_TEMP_GEN_0;

    static private Body Body_TEMP_STATIC_GEN_0;

    static private TransformedShape TransformedShape_TEMP_STATIC_GEN_0;

    static public final TransformedShapeCollector NULL = TransformedShapeCollector.native_new();

    /*[-JNI;-NATIVE]
class TransformedShapeCollectorJS : public TransformedShapeCollector {
private:
	JNIEnv* env;
	jobject obj;
public:
	inline static jclass jClassID = 0;
	inline static jmethodID Reset_ID = 0;
	inline static jmethodID OnBodyJ_ID = 0;
	inline static jmethodID AddHitJ_ID = 0;

void setupCallback(JNIEnv* env, jobject obj) {
	this->env = env;
	this->obj = env->NewGlobalRef(obj);
	if(TransformedShapeCollectorJS::jClassID == 0) {
		TransformedShapeCollectorJS::jClassID = (jclass)env->NewGlobalRef(env->GetObjectClass(obj));
		TransformedShapeCollectorJS::Reset_ID = env->GetMethodID(jClassID, "internal_Reset", "()V");
		TransformedShapeCollectorJS::OnBodyJ_ID = env->GetMethodID(jClassID, "internal_OnBody", "(J)V");
		TransformedShapeCollectorJS::AddHitJ_ID = env->GetMethodID(jClassID, "internal_AddHit", "(J)V");
	}
}
virtual void Reset() {
   env->CallVoidMethod(obj, TransformedShapeCollectorJS::Reset_ID);
}
virtual void OnBody(const Body& inBody) {
   env->CallVoidMethod(obj, TransformedShapeCollectorJS::OnBodyJ_ID, (jlong)&inBody);
}
virtual void AddHit(const TransformedShape& inResult) {
   env->CallVoidMethod(obj, TransformedShapeCollectorJS::AddHitJ_ID, (jlong)&inResult);
}
};
*/
    @Deprecated()
    protected TransformedShapeCollector(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static TransformedShapeCollector native_new() {
        return new TransformedShapeCollector((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
TransformedShapeCollectorJS* nativeObject = (TransformedShapeCollectorJS*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void SetContext(TransformedShape inContext) {
        internal_native_SetContext(native_address, inContext.native_address);
    }

    /*[-JNI;-NATIVE]
TransformedShapeCollector* nativeObject = (TransformedShapeCollector*)this_addr;
nativeObject->SetContext((TransformedShape* )inContext_addr);
*/
    public static native void internal_native_SetContext(long this_addr, long inContext_addr);

    public TransformedShape GetContext() {
        long pointer = internal_native_GetContext(native_address);
        if (pointer == 0)
            return TransformedShape.NULL;
        if (TransformedShape_TEMP_GEN_0 == null)
            TransformedShape_TEMP_GEN_0 = TransformedShape.native_new();
        TransformedShape_TEMP_GEN_0.internal_reset(pointer, false);
        return TransformedShape_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
TransformedShapeCollector* nativeObject = (TransformedShapeCollector*)this_addr;
const TransformedShape* obj = nativeObject->GetContext();
return (jlong)obj;
*/
    public static native long internal_native_GetContext(long this_addr);

    public void UpdateEarlyOutFraction(float inFraction) {
        internal_native_UpdateEarlyOutFraction(native_address, inFraction);
    }

    /*[-JNI;-NATIVE]
TransformedShapeCollector* nativeObject = (TransformedShapeCollector*)this_addr;
nativeObject->UpdateEarlyOutFraction((float)inFraction);
*/
    public static native void internal_native_UpdateEarlyOutFraction(long this_addr, float inFraction);

    public void ResetEarlyOutFraction(float inFraction) {
        internal_native_ResetEarlyOutFraction(native_address, inFraction);
    }

    /*[-JNI;-NATIVE]
TransformedShapeCollector* nativeObject = (TransformedShapeCollector*)this_addr;
nativeObject->ResetEarlyOutFraction((float)inFraction);
*/
    public static native void internal_native_ResetEarlyOutFraction(long this_addr, float inFraction);

    public void ResetEarlyOutFraction() {
        internal_native_ResetEarlyOutFraction(native_address);
    }

    /*[-JNI;-NATIVE]
TransformedShapeCollector* nativeObject = (TransformedShapeCollector*)this_addr;
nativeObject->ResetEarlyOutFraction();
*/
    public static native void internal_native_ResetEarlyOutFraction(long this_addr);

    public void ForceEarlyOut() {
        internal_native_ForceEarlyOut(native_address);
    }

    /*[-JNI;-NATIVE]
TransformedShapeCollector* nativeObject = (TransformedShapeCollector*)this_addr;
nativeObject->ForceEarlyOut();
*/
    public static native void internal_native_ForceEarlyOut(long this_addr);

    public boolean ShouldEarlyOut() {
        return internal_native_ShouldEarlyOut(native_address);
    }

    /*[-JNI;-NATIVE]
TransformedShapeCollector* nativeObject = (TransformedShapeCollector*)this_addr;
return nativeObject->ShouldEarlyOut();
*/
    public static native boolean internal_native_ShouldEarlyOut(long this_addr);

    public float GetEarlyOutFraction() {
        return internal_native_GetEarlyOutFraction(native_address);
    }

    /*[-JNI;-NATIVE]
TransformedShapeCollector* nativeObject = (TransformedShapeCollector*)this_addr;
return nativeObject->GetEarlyOutFraction();
*/
    public static native float internal_native_GetEarlyOutFraction(long this_addr);

    public float GetPositiveEarlyOutFraction() {
        return internal_native_GetPositiveEarlyOutFraction(native_address);
    }

    /*[-JNI;-NATIVE]
TransformedShapeCollector* nativeObject = (TransformedShapeCollector*)this_addr;
return nativeObject->GetPositiveEarlyOutFraction();
*/
    public static native float internal_native_GetPositiveEarlyOutFraction(long this_addr);

    public TransformedShapeCollector() {
        long addr = internal_native_create();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        internal_native_setupCallback(native_address);
    }

    protected void Reset() {
    }

    private void internal_Reset() {
        Reset();
    }

    protected void OnBody(Body inBody) {
    }

    private void internal_OnBody(long inBody_addr) {
        if (Body_TEMP_STATIC_GEN_0 == null)
            Body_TEMP_STATIC_GEN_0 = Body.native_new();
        Body_TEMP_STATIC_GEN_0.internal_reset(inBody_addr, false);
        OnBody(Body_TEMP_STATIC_GEN_0);
    }

    protected void AddHit(TransformedShape inResult) {
    }

    private void internal_AddHit(long inResult_addr) {
        if (TransformedShape_TEMP_STATIC_GEN_0 == null)
            TransformedShape_TEMP_STATIC_GEN_0 = TransformedShape.native_new();
        TransformedShape_TEMP_STATIC_GEN_0.internal_reset(inResult_addr, false);
        AddHit(TransformedShape_TEMP_STATIC_GEN_0);
    }

    /*[-JNI;-NATIVE]
return (jlong)new TransformedShapeCollectorJS();
*/
    public static native long internal_native_create();

    /*[-JNI;-NATIVE]
TransformedShapeCollectorJS* nativeObject = (TransformedShapeCollectorJS*)this_addr;
nativeObject->setupCallback(env, object);
*/
    public native void internal_native_setupCallback(long this_addr);
}
