/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.raddoll;

import jolt.physics.body.BodyCreationSettings;
import jolt.math.TwoBodyConstraintSettings;

public class RagdollPart extends BodyCreationSettings {

    private TwoBodyConstraintSettings TwoBodyConstraintSettings_TEMP_GEN_0;

    static public final RagdollPart T_01 = new RagdollPart((byte) 1, (char) 1);

    static public final RagdollPart T_02 = new RagdollPart((byte) 1, (char) 1);

    static public final RagdollPart T_03 = new RagdollPart((byte) 1, (char) 1);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public RagdollPart(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
RagdollPart* nativeObject = (RagdollPart*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public TwoBodyConstraintSettings get_mToParent() {
        long pointer = internal_native_get_mToParent(native_address);
        if (pointer == 0)
            return null;
        if (TwoBodyConstraintSettings_TEMP_GEN_0 == null)
            TwoBodyConstraintSettings_TEMP_GEN_0 = new TwoBodyConstraintSettings((byte) 1, (char) 1);
        TwoBodyConstraintSettings_TEMP_GEN_0.internal_reset(pointer, false);
        return TwoBodyConstraintSettings_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
RagdollPart* nativeObject = (RagdollPart*)this_addr;
TwoBodyConstraintSettings* attr = nativeObject->mToParent;
return (jlong)attr;
*/
    public static native long internal_native_get_mToParent(long this_addr);

    public void set_mToParent(TwoBodyConstraintSettings mToParent) {
        internal_native_set_mToParent(native_address, (mToParent != null ? mToParent.native_address : 0));
    }

    /*[-JNI;-NATIVE]
RagdollPart* nativeObject = (RagdollPart*)this_addr;
nativeObject->mToParent = (TwoBodyConstraintSettings*)mToParent_addr;
*/
    public static native void internal_native_set_mToParent(long this_addr, long mToParent_addr);
}
