/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.math;

import com.github.xpenatan.jParser.idl.IDLBase;

public class FloatMemRef extends IDLBase {

    static public final FloatMemRef NULL = FloatMemRef.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected FloatMemRef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static FloatMemRef native_new() {
        return new FloatMemRef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
FloatMemRef* nativeObject = (FloatMemRef*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
