/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.math;

import jolt.idl.IDLBase;

public class Uint8MemRef extends IDLBase {

    static public final Uint8MemRef T_01 = new Uint8MemRef((byte) 1, (char) 1);

    static public final Uint8MemRef T_02 = new Uint8MemRef((byte) 1, (char) 1);

    static public final Uint8MemRef T_03 = new Uint8MemRef((byte) 1, (char) 1);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public Uint8MemRef(byte b, char c) {
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
Uint8MemRef* nativeObject = (Uint8MemRef*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
