/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.math;

import jolt.idl.IDLBase;

public class UintMemRef extends IDLBase {

    static public final UintMemRef NULL = UintMemRef.createInstance();

    static public final UintMemRef T_01 = UintMemRef.createInstance();

    static public final UintMemRef T_02 = UintMemRef.createInstance();

    static public final UintMemRef T_03 = UintMemRef.createInstance();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected UintMemRef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static UintMemRef createInstance() {
        return new UintMemRef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
UintMemRef* nativeObject = (UintMemRef*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
