/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package jolt.math;

import jolt.idl.IDLBase;

public class Vec3 extends IDLBase {

    static private Vec3 Vec3_TEMP_STATIC_GEN_0;

    static private Vec3 Vec3_TEMP_STATIC_GEN_1;

    static private Vec3 Vec3_TEMP_STATIC_GEN_2;

    static private Vec3 Vec3_TEMP_STATIC_GEN_3;

    static private Vec3 Vec3_TEMP_STATIC_GEN_4;

    static private Vec3 Vec3_TEMP_STATIC_GEN_5;

    static private Vec3 Vec3_TEMP_STATIC_GEN_6;

    static private Vec3 Vec3_TEMP_STATIC_GEN_7;

    static private Vec3 Vec3_TEMP_STATIC_GEN_8;

    static private Vec3 Vec3_TEMP_STATIC_GEN_9;

    static private Vec3 Vec3_TEMP_STATIC_GEN_10;

    static private Vec3 Vec3_TEMP_STATIC_GEN_11;

    static private Vec3 Vec3_TEMP_STATIC_GEN_12;

    static private Vec3 Vec3_TEMP_STATIC_GEN_13;

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    private Vec3 Vec3_TEMP_GEN_2;

    private Vec3 Vec3_TEMP_GEN_3;

    private Vec3 Vec3_TEMP_GEN_4;

    private Vec3 Vec3_TEMP_GEN_5;

    private Vec3 Vec3_TEMP_GEN_6;

    private Vec4 Vec4_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_7;

    private Vec3 Vec3_TEMP_GEN_8;

    private Vec3 Vec3_TEMP_GEN_9;

    private Vec3 Vec3_TEMP_GEN_10;

    private Vec3 Vec3_TEMP_GEN_11;

    private Vec3 Vec3_TEMP_GEN_12;

    private Vec4 Vec4_TEMP_GEN_1;

    private Vec4 Vec4_TEMP_GEN_2;

    private Vec4 Vec4_TEMP_GEN_3;

    private Vec3 Vec3_TEMP_GEN_13;

    private Vec3 Vec3_TEMP_GEN_14;

    @Override
    public String toString() {
        return "X: " + GetX() + " Y: " + GetY() + " Z: " + GetZ();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public Vec3(byte b, char c) {
    }

    public void dispose() {
        super.dispose();
    }

    public boolean isDisposed() {
        return super.isDisposed();
    }

    protected void deleteNative() {
        internal_native_deleteNative((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      delete nativeObject;
    */
    private static native void internal_native_deleteNative(long this_addr);

    public static Vec3 sZero() {
        long pointer = internal_native_sZero();
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_0 == null)
            Vec3_TEMP_STATIC_GEN_0 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_0.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_0;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sZero();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sZero();

    public static Vec3 sOne() {
        long pointer = internal_native_sOne();
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_1 == null)
            Vec3_TEMP_STATIC_GEN_1 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_1.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_1;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sOne();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sOne();

    public static Vec3 sAxisX() {
        long pointer = internal_native_sAxisX();
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_2 == null)
            Vec3_TEMP_STATIC_GEN_2 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_2.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_2;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sAxisX();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sAxisX();

    public static Vec3 sAxisY() {
        long pointer = internal_native_sAxisY();
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_3 == null)
            Vec3_TEMP_STATIC_GEN_3 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_3.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_3;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sAxisY();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sAxisY();

    public static Vec3 sAxisZ() {
        long pointer = internal_native_sAxisZ();
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_4 == null)
            Vec3_TEMP_STATIC_GEN_4 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_4.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_4;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sAxisZ();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sAxisZ();

    public static Vec3 sReplicate(float inValue) {
        long pointer = internal_native_sReplicate(inValue);
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_5 == null)
            Vec3_TEMP_STATIC_GEN_5 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_5.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_5;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sReplicate((float)inValue);
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sReplicate(float inValue);

    public static Vec3 sMin(Vec3 inLHS, Vec3 inRHS) {
        long pointer = internal_native_sMin((long) (inLHS != null ? inLHS.getNativeData().getCPointer() : 0), (long) (inRHS != null ? inRHS.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_6 == null)
            Vec3_TEMP_STATIC_GEN_6 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_6.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_6;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sMin(*((Vec3* )inLHS_addr), *((Vec3* )inRHS_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sMin(long inLHS_addr, long inRHS_addr);

    public static Vec3 sMax(Vec3 inLHS, Vec3 inRHS) {
        long pointer = internal_native_sMax((long) (inLHS != null ? inLHS.getNativeData().getCPointer() : 0), (long) (inRHS != null ? inRHS.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_7 == null)
            Vec3_TEMP_STATIC_GEN_7 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_7.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_7;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sMax(*((Vec3* )inLHS_addr), *((Vec3* )inRHS_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sMax(long inLHS_addr, long inRHS_addr);

    public static Vec3 sClamp(Vec3 inValue, Vec3 inMin, Vec3 inMax) {
        long pointer = internal_native_sClamp((long) (inValue != null ? inValue.getNativeData().getCPointer() : 0), (long) (inMin != null ? inMin.getNativeData().getCPointer() : 0), (long) (inMax != null ? inMax.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_8 == null)
            Vec3_TEMP_STATIC_GEN_8 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_8.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_8;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sClamp(*((Vec3* )inValue_addr), *((Vec3* )inMin_addr), *((Vec3* )inMax_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sClamp(long inValue_addr, long inMin_addr, long inMax_addr);

    public static Vec3 sFusedMultiplyAdd(Vec3 inMul1, Vec3 inMul2, Vec3 inAdd) {
        long pointer = internal_native_sFusedMultiplyAdd((long) (inMul1 != null ? inMul1.getNativeData().getCPointer() : 0), (long) (inMul2 != null ? inMul2.getNativeData().getCPointer() : 0), (long) (inAdd != null ? inAdd.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_9 == null)
            Vec3_TEMP_STATIC_GEN_9 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_9.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_9;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sFusedMultiplyAdd(*((Vec3* )inMul1_addr), *((Vec3* )inMul2_addr), *((Vec3* )inAdd_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sFusedMultiplyAdd(long inMul1_addr, long inMul2_addr, long inAdd_addr);

    public static Vec3 sOr(Vec3 inV1, Vec3 inV2) {
        long pointer = internal_native_sOr((long) (inV1 != null ? inV1.getNativeData().getCPointer() : 0), (long) (inV2 != null ? inV2.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_10 == null)
            Vec3_TEMP_STATIC_GEN_10 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_10.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_10;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sOr(*((Vec3* )inV1_addr), *((Vec3* )inV2_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sOr(long inV1_addr, long inV2_addr);

    public static Vec3 sXor(Vec3 inV1, Vec3 inV2) {
        long pointer = internal_native_sXor((long) (inV1 != null ? inV1.getNativeData().getCPointer() : 0), (long) (inV2 != null ? inV2.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_11 == null)
            Vec3_TEMP_STATIC_GEN_11 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_11.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_11;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sXor(*((Vec3* )inV1_addr), *((Vec3* )inV2_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sXor(long inV1_addr, long inV2_addr);

    public static Vec3 sAnd(Vec3 inV1, Vec3 inV2) {
        long pointer = internal_native_sAnd((long) (inV1 != null ? inV1.getNativeData().getCPointer() : 0), (long) (inV2 != null ? inV2.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_12 == null)
            Vec3_TEMP_STATIC_GEN_12 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_12.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_12;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sAnd(*((Vec3* )inV1_addr), *((Vec3* )inV2_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sAnd(long inV1_addr, long inV2_addr);

    public static Vec3 sUnitSpherical(float inTheta, float inPhi) {
        long pointer = internal_native_sUnitSpherical(inTheta, inPhi);
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_STATIC_GEN_13 == null)
            Vec3_TEMP_STATIC_GEN_13 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_STATIC_GEN_13.getNativeData().reset(pointer, false);
        return Vec3_TEMP_STATIC_GEN_13;
    }

    /*
      [-JNI;-NATIVE]
      static Vec3 copy_addr;
      copy_addr = Vec3::sUnitSpherical((float)inTheta, (float)inPhi);
      return (jlong)&copy_addr;
    */
    private static native long internal_native_sUnitSpherical(float inTheta, float inPhi);

    public float GetComponent(int inCoordinate) {
        return internal_native_GetComponent((long) getNativeData().getCPointer(), inCoordinate);
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return ((*nativeObject)[inCoordinate]);
    */
    private static native float internal_native_GetComponent(long this_addr, int inCoordinate);

    public boolean Equals(Vec3 inV) {
        return internal_native_Equals((long) getNativeData().getCPointer(), (long) (inV != null ? inV.getNativeData().getCPointer() : 0));
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return ((*nativeObject == *((Vec3* )inV_addr)));
    */
    private static native boolean internal_native_Equals(long this_addr, long inV_addr);

    public boolean NotEquals(Vec3 inV) {
        return internal_native_NotEquals((long) getNativeData().getCPointer(), (long) (inV != null ? inV.getNativeData().getCPointer() : 0));
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return ((*nativeObject != *((Vec3* )inV_addr)));
    */
    private static native boolean internal_native_NotEquals(long this_addr, long inV_addr);

    public float LengthSq() {
        return internal_native_LengthSq((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->LengthSq();
    */
    private static native float internal_native_LengthSq(long this_addr);

    public float Length() {
        return internal_native_Length((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->Length();
    */
    private static native float internal_native_Length(long this_addr);

    public Vec3 Normalized() {
        long pointer = internal_native_Normalized((long) getNativeData().getCPointer());
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_0.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_0;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = nativeObject->Normalized();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_Normalized(long this_addr);

    public Vec3 NormalizedOr(Vec3 inZeroValue) {
        long pointer = internal_native_NormalizedOr((long) getNativeData().getCPointer(), (long) (inZeroValue != null ? inZeroValue.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_1.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_1;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = nativeObject->NormalizedOr(*((Vec3* )inZeroValue_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_NormalizedOr(long this_addr, long inZeroValue_addr);

    public Vec3 GetNormalizedPerpendicular() {
        long pointer = internal_native_GetNormalizedPerpendicular((long) getNativeData().getCPointer());
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_2 == null)
            Vec3_TEMP_GEN_2 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_2.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_2;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = nativeObject->GetNormalizedPerpendicular();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_GetNormalizedPerpendicular(long this_addr);

    public float GetX() {
        return internal_native_GetX((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->GetX();
    */
    private static native float internal_native_GetX(long this_addr);

    public float GetY() {
        return internal_native_GetY((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->GetY();
    */
    private static native float internal_native_GetY(long this_addr);

    public float GetZ() {
        return internal_native_GetZ((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->GetZ();
    */
    private static native float internal_native_GetZ(long this_addr);

    public void SetX(float inX) {
        internal_native_SetX((long) getNativeData().getCPointer(), inX);
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      nativeObject->SetX((float)inX);
    */
    private static native void internal_native_SetX(long this_addr, float inX);

    public void SetY(float inY) {
        internal_native_SetY((long) getNativeData().getCPointer(), inY);
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      nativeObject->SetY((float)inY);
    */
    private static native void internal_native_SetY(long this_addr, float inY);

    public void SetZ(float inZ) {
        internal_native_SetZ((long) getNativeData().getCPointer(), inZ);
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      nativeObject->SetZ((float)inZ);
    */
    private static native void internal_native_SetZ(long this_addr, float inZ);

    public void Set(float inX, float inY, float inZ) {
        internal_native_Set((long) getNativeData().getCPointer(), inX, inY, inZ);
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      nativeObject->Set((float)inX, (float)inY, (float)inZ);
    */
    private static native void internal_native_Set(long this_addr, float inX, float inY, float inZ);

    public void SetComponent(int inCoordinate, float inValue) {
        internal_native_SetComponent((long) getNativeData().getCPointer(), inCoordinate, inValue);
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      nativeObject->SetComponent(inCoordinate, (float)inValue);
    */
    private static native void internal_native_SetComponent(long this_addr, int inCoordinate, float inValue);

    public boolean IsNearZero(float inMaxDistSq) {
        return internal_native_IsNearZero((long) getNativeData().getCPointer(), inMaxDistSq);
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->IsNearZero((float)inMaxDistSq);
    */
    private static native boolean internal_native_IsNearZero(long this_addr, float inMaxDistSq);

    public boolean IsNearZero() {
        return internal_native_IsNearZero((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->IsNearZero();
    */
    private static native boolean internal_native_IsNearZero(long this_addr);

    public boolean IsClose(Vec3 inV, float inMaxDistSq) {
        return internal_native_IsClose((long) getNativeData().getCPointer(), (long) (inV != null ? inV.getNativeData().getCPointer() : 0), inMaxDistSq);
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->IsClose(*((Vec3* )inV_addr), (float)inMaxDistSq);
    */
    private static native boolean internal_native_IsClose(long this_addr, long inV_addr, float inMaxDistSq);

    public boolean IsClose(Vec3 inV) {
        return internal_native_IsClose((long) getNativeData().getCPointer(), (long) (inV != null ? inV.getNativeData().getCPointer() : 0));
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->IsClose(*((Vec3* )inV_addr));
    */
    private static native boolean internal_native_IsClose(long this_addr, long inV_addr);

    public boolean IsNormalized(float inTolerance) {
        return internal_native_IsNormalized((long) getNativeData().getCPointer(), inTolerance);
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->IsNormalized((float)inTolerance);
    */
    private static native boolean internal_native_IsNormalized(long this_addr, float inTolerance);

    public boolean IsNormalized() {
        return internal_native_IsNormalized((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->IsNormalized();
    */
    private static native boolean internal_native_IsNormalized(long this_addr);

    public int GetLowestComponentIndex() {
        return internal_native_GetLowestComponentIndex((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->GetLowestComponentIndex();
    */
    private static native int internal_native_GetLowestComponentIndex(long this_addr);

    public int GetHighestComponentIndex() {
        return internal_native_GetHighestComponentIndex((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->GetHighestComponentIndex();
    */
    private static native int internal_native_GetHighestComponentIndex(long this_addr);

    public Vec3 Abs() {
        long pointer = internal_native_Abs((long) getNativeData().getCPointer());
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_3 == null)
            Vec3_TEMP_GEN_3 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_3.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_3;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = nativeObject->Abs();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_Abs(long this_addr);

    public Vec3 Reciprocal() {
        long pointer = internal_native_Reciprocal((long) getNativeData().getCPointer());
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_4 == null)
            Vec3_TEMP_GEN_4 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_4.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_4;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = nativeObject->Reciprocal();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_Reciprocal(long this_addr);

    public Vec3 Cross(Vec3 inRHS) {
        long pointer = internal_native_Cross((long) getNativeData().getCPointer(), (long) (inRHS != null ? inRHS.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_5 == null)
            Vec3_TEMP_GEN_5 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_5.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_5;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = nativeObject->Cross(*((Vec3* )inRHS_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_Cross(long this_addr, long inRHS_addr);

    public float Dot(Vec3 inRHS) {
        return internal_native_Dot((long) getNativeData().getCPointer(), (long) (inRHS != null ? inRHS.getNativeData().getCPointer() : 0));
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->Dot(*((Vec3* )inRHS_addr));
    */
    private static native float internal_native_Dot(long this_addr, long inRHS_addr);

    public Vec3 DotV(Vec3 inRHS) {
        long pointer = internal_native_DotV((long) getNativeData().getCPointer(), (long) (inRHS != null ? inRHS.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_6 == null)
            Vec3_TEMP_GEN_6 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_6.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_6;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = nativeObject->DotV(*((Vec3* )inRHS_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_DotV(long this_addr, long inRHS_addr);

    public Vec4 DotV4(Vec3 inRHS) {
        long pointer = internal_native_DotV4((long) getNativeData().getCPointer(), (long) (inRHS != null ? inRHS.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec4_TEMP_GEN_0 == null)
            Vec4_TEMP_GEN_0 = new Vec4((byte) 1, (char) 1);
        Vec4_TEMP_GEN_0.getNativeData().reset(pointer, false);
        return Vec4_TEMP_GEN_0;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec4 copy_addr;
      copy_addr = nativeObject->DotV4(*((Vec3* )inRHS_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_DotV4(long this_addr, long inRHS_addr);

    public Vec3 Add(Vec3 inV) {
        internal_native_Add((long) getNativeData().getCPointer(), (long) (inV != null ? inV.getNativeData().getCPointer() : 0));
        return this;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return (jlong)&(*nativeObject += *((Vec3* )inV_addr));
    */
    private static native long internal_native_Add(long this_addr, long inV_addr);

    public Vec3 Sub(Vec3 inV) {
        internal_native_Sub((long) getNativeData().getCPointer(), (long) (inV != null ? inV.getNativeData().getCPointer() : 0));
        return this;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return (jlong)&(*nativeObject -= *((Vec3* )inV_addr));
    */
    private static native long internal_native_Sub(long this_addr, long inV_addr);

    public Vec3 Mul(float inV) {
        internal_native_Mul((long) getNativeData().getCPointer(), inV);
        return this;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return (jlong)&(*nativeObject *= (float)inV);
    */
    private static native long internal_native_Mul(long this_addr, float inV);

    public Vec3 Div(float inV) {
        internal_native_Div((long) getNativeData().getCPointer(), inV);
        return this;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return (jlong)&(*nativeObject /= (float)inV);
    */
    private static native long internal_native_Div(long this_addr, float inV);

    public Vec3 MulVec3(Vec3 inV) {
        long pointer = internal_native_MulVec3((long) getNativeData().getCPointer(), (long) (inV != null ? inV.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_7 == null)
            Vec3_TEMP_GEN_7 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_7.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_7;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = (*nativeObject * *((Vec3* )inV_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_MulVec3(long this_addr, long inV_addr);

    public Vec3 MulFloat(float inV) {
        long pointer = internal_native_MulFloat((long) getNativeData().getCPointer(), inV);
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_8 == null)
            Vec3_TEMP_GEN_8 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_8.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_8;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = (*nativeObject * (float)inV);
      return (jlong)&copy_addr;
    */
    private static native long internal_native_MulFloat(long this_addr, float inV);

    public Vec3 DivVec3(Vec3 inV) {
        long pointer = internal_native_DivVec3((long) getNativeData().getCPointer(), (long) (inV != null ? inV.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_9 == null)
            Vec3_TEMP_GEN_9 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_9.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_9;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = (*nativeObject / *((Vec3* )inV_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_DivVec3(long this_addr, long inV_addr);

    public Vec3 DivFloat(float inV) {
        long pointer = internal_native_DivFloat((long) getNativeData().getCPointer(), inV);
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_10 == null)
            Vec3_TEMP_GEN_10 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_10.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_10;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = (*nativeObject / (float)inV);
      return (jlong)&copy_addr;
    */
    private static native long internal_native_DivFloat(long this_addr, float inV);

    public Vec3 AddVec3(Vec3 inV) {
        long pointer = internal_native_AddVec3((long) getNativeData().getCPointer(), (long) (inV != null ? inV.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_11 == null)
            Vec3_TEMP_GEN_11 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_11.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_11;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = (*nativeObject + *((Vec3* )inV_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_AddVec3(long this_addr, long inV_addr);

    public Vec3 SubVec3(Vec3 inV) {
        long pointer = internal_native_SubVec3((long) getNativeData().getCPointer(), (long) (inV != null ? inV.getNativeData().getCPointer() : 0));
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_12 == null)
            Vec3_TEMP_GEN_12 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_12.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_12;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = (*nativeObject - *((Vec3* )inV_addr));
      return (jlong)&copy_addr;
    */
    private static native long internal_native_SubVec3(long this_addr, long inV_addr);

    public Vec4 SplatX() {
        long pointer = internal_native_SplatX((long) getNativeData().getCPointer());
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec4_TEMP_GEN_1 == null)
            Vec4_TEMP_GEN_1 = new Vec4((byte) 1, (char) 1);
        Vec4_TEMP_GEN_1.getNativeData().reset(pointer, false);
        return Vec4_TEMP_GEN_1;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec4 copy_addr;
      copy_addr = nativeObject->SplatX();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_SplatX(long this_addr);

    public Vec4 SplatY() {
        long pointer = internal_native_SplatY((long) getNativeData().getCPointer());
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec4_TEMP_GEN_2 == null)
            Vec4_TEMP_GEN_2 = new Vec4((byte) 1, (char) 1);
        Vec4_TEMP_GEN_2.getNativeData().reset(pointer, false);
        return Vec4_TEMP_GEN_2;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec4 copy_addr;
      copy_addr = nativeObject->SplatY();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_SplatY(long this_addr);

    public Vec4 SplatZ() {
        long pointer = internal_native_SplatZ((long) getNativeData().getCPointer());
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec4_TEMP_GEN_3 == null)
            Vec4_TEMP_GEN_3 = new Vec4((byte) 1, (char) 1);
        Vec4_TEMP_GEN_3.getNativeData().reset(pointer, false);
        return Vec4_TEMP_GEN_3;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec4 copy_addr;
      copy_addr = nativeObject->SplatZ();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_SplatZ(long this_addr);

    public float ReduceMin() {
        return internal_native_ReduceMin((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->ReduceMin();
    */
    private static native float internal_native_ReduceMin(long this_addr);

    public float ReduceMax() {
        return internal_native_ReduceMax((long) getNativeData().getCPointer());
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      return nativeObject->ReduceMax();
    */
    private static native float internal_native_ReduceMax(long this_addr);

    public Vec3 Sqrt() {
        long pointer = internal_native_Sqrt((long) getNativeData().getCPointer());
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_13 == null)
            Vec3_TEMP_GEN_13 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_13.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_13;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = nativeObject->Sqrt();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_Sqrt(long this_addr);

    public Vec3 GetSign() {
        long pointer = internal_native_GetSign((long) getNativeData().getCPointer());
        if (pointer == 0)
            throw new RuntimeException("Pointer is null");
        if (Vec3_TEMP_GEN_14 == null)
            Vec3_TEMP_GEN_14 = new Vec3((byte) 1, (char) 1);
        Vec3_TEMP_GEN_14.getNativeData().reset(pointer, false);
        return Vec3_TEMP_GEN_14;
    }

    /*
      [-JNI;-NATIVE]
      Vec3* nativeObject = (Vec3*)this_addr;
      static Vec3 copy_addr;
      copy_addr = nativeObject->GetSign();
      return (jlong)&copy_addr;
    */
    private static native long internal_native_GetSign(long this_addr);

    public static void native_deleteNative(long this_addr) {
        internal_native_deleteNative(this_addr);
    }

    public static long native_sZero() {
        return internal_native_sZero();
    }

    public static long native_sOne() {
        return internal_native_sOne();
    }

    public static long native_sAxisX() {
        return internal_native_sAxisX();
    }

    public static long native_sAxisY() {
        return internal_native_sAxisY();
    }

    public static long native_sAxisZ() {
        return internal_native_sAxisZ();
    }

    public static long native_sReplicate(float inValue) {
        return internal_native_sReplicate(inValue);
    }

    public static long native_sMin(long inLHS_addr, long inRHS_addr) {
        return internal_native_sMin(inLHS_addr, inRHS_addr);
    }

    public static long native_sMax(long inLHS_addr, long inRHS_addr) {
        return internal_native_sMax(inLHS_addr, inRHS_addr);
    }

    public static long native_sClamp(long inValue_addr, long inMin_addr, long inMax_addr) {
        return internal_native_sClamp(inValue_addr, inMin_addr, inMax_addr);
    }

    public static long native_sFusedMultiplyAdd(long inMul1_addr, long inMul2_addr, long inAdd_addr) {
        return internal_native_sFusedMultiplyAdd(inMul1_addr, inMul2_addr, inAdd_addr);
    }

    public static long native_sOr(long inV1_addr, long inV2_addr) {
        return internal_native_sOr(inV1_addr, inV2_addr);
    }

    public static long native_sXor(long inV1_addr, long inV2_addr) {
        return internal_native_sXor(inV1_addr, inV2_addr);
    }

    public static long native_sAnd(long inV1_addr, long inV2_addr) {
        return internal_native_sAnd(inV1_addr, inV2_addr);
    }

    public static long native_sUnitSpherical(float inTheta, float inPhi) {
        return internal_native_sUnitSpherical(inTheta, inPhi);
    }

    public static float native_GetComponent(long this_addr, int inCoordinate) {
        return internal_native_GetComponent(this_addr, inCoordinate);
    }

    public static boolean native_Equals(long this_addr, long inV_addr) {
        return internal_native_Equals(this_addr, inV_addr);
    }

    public static boolean native_NotEquals(long this_addr, long inV_addr) {
        return internal_native_NotEquals(this_addr, inV_addr);
    }

    public static float native_LengthSq(long this_addr) {
        return internal_native_LengthSq(this_addr);
    }

    public static float native_Length(long this_addr) {
        return internal_native_Length(this_addr);
    }

    public static long native_Normalized(long this_addr) {
        return internal_native_Normalized(this_addr);
    }

    public static long native_NormalizedOr(long this_addr, long inZeroValue_addr) {
        return internal_native_NormalizedOr(this_addr, inZeroValue_addr);
    }

    public static long native_GetNormalizedPerpendicular(long this_addr) {
        return internal_native_GetNormalizedPerpendicular(this_addr);
    }

    public static float native_GetX(long this_addr) {
        return internal_native_GetX(this_addr);
    }

    public static float native_GetY(long this_addr) {
        return internal_native_GetY(this_addr);
    }

    public static float native_GetZ(long this_addr) {
        return internal_native_GetZ(this_addr);
    }

    public static void native_SetX(long this_addr, float inX) {
        internal_native_SetX(this_addr, inX);
    }

    public static void native_SetY(long this_addr, float inY) {
        internal_native_SetY(this_addr, inY);
    }

    public static void native_SetZ(long this_addr, float inZ) {
        internal_native_SetZ(this_addr, inZ);
    }

    public static void native_Set(long this_addr, float inX, float inY, float inZ) {
        internal_native_Set(this_addr, inX, inY, inZ);
    }

    public static void native_SetComponent(long this_addr, int inCoordinate, float inValue) {
        internal_native_SetComponent(this_addr, inCoordinate, inValue);
    }

    public static boolean native_IsNearZero(long this_addr, float inMaxDistSq) {
        return internal_native_IsNearZero(this_addr, inMaxDistSq);
    }

    public static boolean native_IsNearZero(long this_addr) {
        return internal_native_IsNearZero(this_addr);
    }

    public static boolean native_IsClose(long this_addr, long inV_addr, float inMaxDistSq) {
        return internal_native_IsClose(this_addr, inV_addr, inMaxDistSq);
    }

    public static boolean native_IsClose(long this_addr, long inV_addr) {
        return internal_native_IsClose(this_addr, inV_addr);
    }

    public static boolean native_IsNormalized(long this_addr, float inTolerance) {
        return internal_native_IsNormalized(this_addr, inTolerance);
    }

    public static boolean native_IsNormalized(long this_addr) {
        return internal_native_IsNormalized(this_addr);
    }

    public static int native_GetLowestComponentIndex(long this_addr) {
        return internal_native_GetLowestComponentIndex(this_addr);
    }

    public static int native_GetHighestComponentIndex(long this_addr) {
        return internal_native_GetHighestComponentIndex(this_addr);
    }

    public static long native_Abs(long this_addr) {
        return internal_native_Abs(this_addr);
    }

    public static long native_Reciprocal(long this_addr) {
        return internal_native_Reciprocal(this_addr);
    }

    public static long native_Cross(long this_addr, long inRHS_addr) {
        return internal_native_Cross(this_addr, inRHS_addr);
    }

    public static float native_Dot(long this_addr, long inRHS_addr) {
        return internal_native_Dot(this_addr, inRHS_addr);
    }

    public static long native_DotV(long this_addr, long inRHS_addr) {
        return internal_native_DotV(this_addr, inRHS_addr);
    }

    public static long native_DotV4(long this_addr, long inRHS_addr) {
        return internal_native_DotV4(this_addr, inRHS_addr);
    }

    public static long native_Add(long this_addr, long inV_addr) {
        return internal_native_Add(this_addr, inV_addr);
    }

    public static long native_Sub(long this_addr, long inV_addr) {
        return internal_native_Sub(this_addr, inV_addr);
    }

    public static long native_Mul(long this_addr, float inV) {
        return internal_native_Mul(this_addr, inV);
    }

    public static long native_Div(long this_addr, float inV) {
        return internal_native_Div(this_addr, inV);
    }

    public static long native_MulVec3(long this_addr, long inV_addr) {
        return internal_native_MulVec3(this_addr, inV_addr);
    }

    public static long native_MulFloat(long this_addr, float inV) {
        return internal_native_MulFloat(this_addr, inV);
    }

    public static long native_DivVec3(long this_addr, long inV_addr) {
        return internal_native_DivVec3(this_addr, inV_addr);
    }

    public static long native_DivFloat(long this_addr, float inV) {
        return internal_native_DivFloat(this_addr, inV);
    }

    public static long native_AddVec3(long this_addr, long inV_addr) {
        return internal_native_AddVec3(this_addr, inV_addr);
    }

    public static long native_SubVec3(long this_addr, long inV_addr) {
        return internal_native_SubVec3(this_addr, inV_addr);
    }

    public static long native_SplatX(long this_addr) {
        return internal_native_SplatX(this_addr);
    }

    public static long native_SplatY(long this_addr) {
        return internal_native_SplatY(this_addr);
    }

    public static long native_SplatZ(long this_addr) {
        return internal_native_SplatZ(this_addr);
    }

    public static float native_ReduceMin(long this_addr) {
        return internal_native_ReduceMin(this_addr);
    }

    public static float native_ReduceMax(long this_addr) {
        return internal_native_ReduceMax(this_addr);
    }

    public static long native_Sqrt(long this_addr) {
        return internal_native_Sqrt(this_addr);
    }

    public static long native_GetSign(long this_addr) {
        return internal_native_GetSign(this_addr);
    }
}
