/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.math;

import jolt.idl.IDLBase;

public class Vec3MemRef extends IDLBase {

    static public final Vec3MemRef T_01 = new Vec3MemRef((byte) 1, (char) 1);

    static public final Vec3MemRef T_02 = new Vec3MemRef((byte) 1, (char) 1);

    static public final Vec3MemRef T_03 = new Vec3MemRef((byte) 1, (char) 1);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public Vec3MemRef(byte b, char c) {
    }

    public void dispose() {
        super.dispose();
    }

    public boolean isDisposed() {
        return super.isDisposed();
    }

    protected void deleteNative() {
        internal_native_deleteNative((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
Vec3MemRef* nativeObject = (Vec3MemRef*)this_addr;
delete nativeObject;
*/
    private static native void internal_native_deleteNative(long this_addr);

    public static void native_deleteNative(long this_addr) {
        internal_native_deleteNative(this_addr);
    }
}
