/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.math;

import jolt.idl.IDLBase;

public class Vec3MemRef extends IDLBase {

    static public final Vec3MemRef NULL = Vec3MemRef.createInstance();

    static public final Vec3MemRef T_01 = Vec3MemRef.createInstance();

    static public final Vec3MemRef T_02 = Vec3MemRef.createInstance();

    static public final Vec3MemRef T_03 = Vec3MemRef.createInstance();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected Vec3MemRef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static Vec3MemRef createInstance() {
        return new Vec3MemRef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
Vec3MemRef* nativeObject = (Vec3MemRef*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
