/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.collision.shape;

import jolt.physics.collision.PhysicsMaterial;

public class ConvexShapeSettings extends ShapeSettings {

    private PhysicsMaterial PhysicsMaterial_TEMP_GEN_0;

    static public final ConvexShapeSettings NULL = ConvexShapeSettings.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ConvexShapeSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static ConvexShapeSettings native_new() {
        return new ConvexShapeSettings((byte) 0, (char) 0);
    }

    public PhysicsMaterial get_mMaterial() {
        long pointer = internal_native_get_mMaterial(native_address);
        if (pointer == 0)
            return PhysicsMaterial.NULL;
        if (PhysicsMaterial_TEMP_GEN_0 == null)
            PhysicsMaterial_TEMP_GEN_0 = PhysicsMaterial.native_new();
        PhysicsMaterial_TEMP_GEN_0.internal_reset(pointer, false);
        return PhysicsMaterial_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ConvexShapeSettings* nativeObject = (ConvexShapeSettings*)this_addr;
const PhysicsMaterial* attr = nativeObject->mMaterial;
return (jlong)attr;
*/
    public static native long internal_native_get_mMaterial(long this_addr);

    public void set_mMaterial(PhysicsMaterial mMaterial) {
        internal_native_set_mMaterial(native_address, mMaterial.native_address);
    }

    /*[-JNI;-NATIVE]
ConvexShapeSettings* nativeObject = (ConvexShapeSettings*)this_addr;
nativeObject->mMaterial = (PhysicsMaterial*)mMaterial_addr;
*/
    public static native void internal_native_set_mMaterial(long this_addr, long mMaterial_addr);

    public float get_mDensity() {
        return internal_native_get_mDensity(native_address);
    }

    /*[-JNI;-NATIVE]
ConvexShapeSettings* nativeObject = (ConvexShapeSettings*)this_addr;
return nativeObject->mDensity;
*/
    public static native float internal_native_get_mDensity(long this_addr);

    public void set_mDensity(float mDensity) {
        internal_native_set_mDensity(native_address, mDensity);
    }

    /*[-JNI;-NATIVE]
ConvexShapeSettings* nativeObject = (ConvexShapeSettings*)this_addr;
nativeObject->mDensity = mDensity;
*/
    public static native void internal_native_set_mDensity(long this_addr, float mDensity);
}
