/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.collision.shape;

import jolt.math.Vec3;
import jolt.math.Quat;
import jolt.math.Vec3MemRef;
import jolt.math.QuatMemRef;

public class MutableCompoundShape extends CompoundShape {

    static public final MutableCompoundShape T_01 = new MutableCompoundShape((byte) 1, (char) 1);

    static public final MutableCompoundShape T_02 = new MutableCompoundShape((byte) 1, (char) 1);

    static public final MutableCompoundShape T_03 = new MutableCompoundShape((byte) 1, (char) 1);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public MutableCompoundShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public int AddShape(Vec3 inPosition, Quat inRotation, Shape inShape, int inUserData) {
        return internal_native_AddShape((long) getNativeData().getCPointer(), (long) (inPosition != null ? inPosition.getNativeData().getCPointer() : 0), (long) (inRotation != null ? inRotation.getNativeData().getCPointer() : 0), (long) (inShape != null ? inShape.getNativeData().getCPointer() : 0), inUserData);
    }

    /*[-JNI;-NATIVE]
MutableCompoundShape* nativeObject = (MutableCompoundShape*)this_addr;
return nativeObject->AddShape(*((Vec3* )inPosition_addr), *((Quat* )inRotation_addr), (Shape* )inShape_addr, inUserData);
*/
    private static native int internal_native_AddShape(long this_addr, long inPosition_addr, long inRotation_addr, long inShape_addr, int inUserData);

    public void RemoveShape(int inIndex) {
        internal_native_RemoveShape((long) getNativeData().getCPointer(), inIndex);
    }

    /*[-JNI;-NATIVE]
MutableCompoundShape* nativeObject = (MutableCompoundShape*)this_addr;
nativeObject->RemoveShape(inIndex);
*/
    private static native void internal_native_RemoveShape(long this_addr, int inIndex);

    public void ModifyShape(int inIndex, Vec3 inPosition, Quat inRotation) {
        internal_native_ModifyShape((long) getNativeData().getCPointer(), inIndex, (long) (inPosition != null ? inPosition.getNativeData().getCPointer() : 0), (long) (inRotation != null ? inRotation.getNativeData().getCPointer() : 0));
    }

    /*[-JNI;-NATIVE]
MutableCompoundShape* nativeObject = (MutableCompoundShape*)this_addr;
nativeObject->ModifyShape(inIndex, *((Vec3* )inPosition_addr), *((Quat* )inRotation_addr));
*/
    private static native void internal_native_ModifyShape(long this_addr, int inIndex, long inPosition_addr, long inRotation_addr);

    public void ModifyShape(int inIndex, Vec3 inPosition, Quat inRotation, Shape inShape) {
        internal_native_ModifyShape((long) getNativeData().getCPointer(), inIndex, (long) (inPosition != null ? inPosition.getNativeData().getCPointer() : 0), (long) (inRotation != null ? inRotation.getNativeData().getCPointer() : 0), (long) (inShape != null ? inShape.getNativeData().getCPointer() : 0));
    }

    /*[-JNI;-NATIVE]
MutableCompoundShape* nativeObject = (MutableCompoundShape*)this_addr;
nativeObject->ModifyShape(inIndex, *((Vec3* )inPosition_addr), *((Quat* )inRotation_addr), (Shape* )inShape_addr);
*/
    private static native void internal_native_ModifyShape(long this_addr, int inIndex, long inPosition_addr, long inRotation_addr, long inShape_addr);

    public void ModifyShapes(int inStartIndex, int inNumber, Vec3MemRef inPositions, QuatMemRef inRotations) {
        internal_native_ModifyShapes((long) getNativeData().getCPointer(), inStartIndex, inNumber, (long) (inPositions != null ? inPositions.getNativeData().getCPointer() : 0), (long) (inRotations != null ? inRotations.getNativeData().getCPointer() : 0));
    }

    /*[-JNI;-NATIVE]
MutableCompoundShape* nativeObject = (MutableCompoundShape*)this_addr;
nativeObject->ModifyShapes(inStartIndex, inNumber, (Vec3MemRef* )inPositions_addr, (QuatMemRef* )inRotations_addr);
*/
    private static native void internal_native_ModifyShapes(long this_addr, int inStartIndex, int inNumber, long inPositions_addr, long inRotations_addr);

    public void AdjustCenterOfMass() {
        internal_native_AdjustCenterOfMass((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
MutableCompoundShape* nativeObject = (MutableCompoundShape*)this_addr;
nativeObject->AdjustCenterOfMass();
*/
    private static native void internal_native_AdjustCenterOfMass(long this_addr);

    public static int native_AddShape(long this_addr, long inPosition_addr, long inRotation_addr, long inShape_addr, int inUserData) {
        return internal_native_AddShape(this_addr, inPosition_addr, inRotation_addr, inShape_addr, inUserData);
    }

    public static void native_RemoveShape(long this_addr, int inIndex) {
        internal_native_RemoveShape(this_addr, inIndex);
    }

    public static void native_ModifyShape(long this_addr, int inIndex, long inPosition_addr, long inRotation_addr) {
        internal_native_ModifyShape(this_addr, inIndex, inPosition_addr, inRotation_addr);
    }

    public static void native_ModifyShape(long this_addr, int inIndex, long inPosition_addr, long inRotation_addr, long inShape_addr) {
        internal_native_ModifyShape(this_addr, inIndex, inPosition_addr, inRotation_addr, inShape_addr);
    }

    public static void native_ModifyShapes(long this_addr, int inStartIndex, int inNumber, long inPositions_addr, long inRotations_addr) {
        internal_native_ModifyShapes(this_addr, inStartIndex, inNumber, inPositions_addr, inRotations_addr);
    }

    public static void native_AdjustCenterOfMass(long this_addr) {
        internal_native_AdjustCenterOfMass(this_addr);
    }
}
