/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.collision.shape;

import jolt.math.Vec3;
import jolt.math.Quat;

public class RotatedTranslatedShapeSettings extends DecoratedShapeSettings {

    private Vec3 Vec3_TEMP_GEN_0;

    private Quat Quat_TEMP_GEN_0;

    static public final RotatedTranslatedShapeSettings NULL = RotatedTranslatedShapeSettings.createInstance();

    static public final RotatedTranslatedShapeSettings T_01 = RotatedTranslatedShapeSettings.createInstance();

    static public final RotatedTranslatedShapeSettings T_02 = RotatedTranslatedShapeSettings.createInstance();

    static public final RotatedTranslatedShapeSettings T_03 = RotatedTranslatedShapeSettings.createInstance();

    public RotatedTranslatedShapeSettings(Vec3 inPosition, Quat inRotation, ShapeSettings inShape) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_Vec3_Quat_ShapeSettings(inPosition.native_address, inRotation.native_address, inShape.native_address);
        internal_reset(addr, false);
    }

    /*[-JNI;-NATIVE]
return (jlong)new RotatedTranslatedShapeSettings(*((Vec3* )inPosition_addr), *((Quat* )inRotation_addr), (ShapeSettings* )inShape_addr);
*/
    public static native long internal_native_create_Vec3_Quat_ShapeSettings(long inPosition_addr, long inRotation_addr, long inShape_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected RotatedTranslatedShapeSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static RotatedTranslatedShapeSettings createInstance() {
        return new RotatedTranslatedShapeSettings((byte) 0, (char) 0);
    }

    public Vec3 get_mPosition() {
        long pointer = internal_native_get_mPosition(native_address);
        if (pointer == 0)
            return null;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.createInstance();
        Vec3_TEMP_GEN_0.internal_reset(pointer, false);
        return Vec3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
RotatedTranslatedShapeSettings* nativeObject = (RotatedTranslatedShapeSettings*)this_addr;
return (jlong)&nativeObject->mPosition;
*/
    public static native long internal_native_get_mPosition(long this_addr);

    public void set_mPosition(Vec3 mPosition) {
        internal_native_set_mPosition(native_address, mPosition.native_address);
    }

    /*[-JNI;-NATIVE]
RotatedTranslatedShapeSettings* nativeObject = (RotatedTranslatedShapeSettings*)this_addr;
nativeObject->mPosition = *((Vec3*)mPosition_addr);
*/
    public static native void internal_native_set_mPosition(long this_addr, long mPosition_addr);

    public Quat get_mRotation() {
        long pointer = internal_native_get_mRotation(native_address);
        if (pointer == 0)
            return null;
        if (Quat_TEMP_GEN_0 == null)
            Quat_TEMP_GEN_0 = Quat.createInstance();
        Quat_TEMP_GEN_0.internal_reset(pointer, false);
        return Quat_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
RotatedTranslatedShapeSettings* nativeObject = (RotatedTranslatedShapeSettings*)this_addr;
return (jlong)&nativeObject->mRotation;
*/
    public static native long internal_native_get_mRotation(long this_addr);

    public void set_mRotation(Quat mRotation) {
        internal_native_set_mRotation(native_address, mRotation.native_address);
    }

    /*[-JNI;-NATIVE]
RotatedTranslatedShapeSettings* nativeObject = (RotatedTranslatedShapeSettings*)this_addr;
nativeObject->mRotation = *((Quat*)mRotation_addr);
*/
    public static native void internal_native_set_mRotation(long this_addr, long mRotation_addr);
}
