/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.vehicle;

import jolt.idl.IDLBase;

public class VehicleController extends IDLBase {

    private VehicleConstraint VehicleConstraint_TEMP_GEN_0;

    static public final VehicleController NULL = VehicleController.native_new();

    static public final VehicleController T_01 = VehicleController.native_new();

    static public final VehicleController T_02 = VehicleController.native_new();

    static public final VehicleController T_03 = VehicleController.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleController(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleController native_new() {
        return new VehicleController((byte) 0, (char) 0);
    }

    public VehicleConstraint GetConstraint() {
        long pointer = internal_native_GetConstraint(native_address);
        if (pointer == 0)
            return null;
        if (VehicleConstraint_TEMP_GEN_0 == null)
            VehicleConstraint_TEMP_GEN_0 = VehicleConstraint.native_new();
        VehicleConstraint_TEMP_GEN_0.internal_reset(pointer, false);
        return VehicleConstraint_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
VehicleController* nativeObject = (VehicleController*)this_addr;
return (jlong)&nativeObject->GetConstraint();
*/
    public static native long internal_native_GetConstraint(long this_addr);
}
