/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.vehicle;

import jolt.idl.IDLBase;
import jolt.enums.ETransmissionMode;
import jolt.math.ArrayFloat;

public class VehicleTransmissionSettings extends IDLBase {

    private ArrayFloat ArrayFloat_TEMP_GEN_0;

    private ArrayFloat ArrayFloat_TEMP_GEN_1;

    static public final VehicleTransmissionSettings T_01 = new VehicleTransmissionSettings((byte) 1, (char) 1);

    static public final VehicleTransmissionSettings T_02 = new VehicleTransmissionSettings((byte) 1, (char) 1);

    static public final VehicleTransmissionSettings T_03 = new VehicleTransmissionSettings((byte) 1, (char) 1);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    public VehicleTransmissionSettings(byte b, char c) {
    }

    public void dispose() {
        super.dispose();
    }

    public boolean isDisposed() {
        return super.isDisposed();
    }

    protected void deleteNative() {
        internal_native_deleteNative((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public ETransmissionMode get_mMode() {
        int value = internal_native_get_mMode((long) getNativeData().getCPointer());
        return ETransmissionMode.MAP.get(value);
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
return (jint)nativeObject->mMode;
*/
    public static native int internal_native_get_mMode(long this_addr);

    public void set_mMode(ETransmissionMode mMode) {
        internal_native_set_mMode((long) getNativeData().getCPointer(), (long) (mMode != null ? mMode.getValue() : 0));
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
nativeObject->mMode = (::ETransmissionMode)mMode;
*/
    public static native void internal_native_set_mMode(long this_addr, long mMode);

    public ArrayFloat get_mGearRatios() {
        long pointer = internal_native_get_mGearRatios((long) getNativeData().getCPointer());
        if (pointer == 0)
            return null;
        if (ArrayFloat_TEMP_GEN_0 == null)
            ArrayFloat_TEMP_GEN_0 = new ArrayFloat((byte) 1, (char) 1);
        ArrayFloat_TEMP_GEN_0.getNativeData().reset(pointer, false);
        return ArrayFloat_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
return (jlong)&nativeObject->mGearRatios;
*/
    public static native long internal_native_get_mGearRatios(long this_addr);

    public void set_mGearRatios(ArrayFloat mGearRatios) {
        internal_native_set_mGearRatios((long) getNativeData().getCPointer(), (long) (mGearRatios != null ? mGearRatios.getNativeData().getCPointer() : 0));
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
nativeObject->mGearRatios = *((ArrayFloat*)mGearRatios_addr);
*/
    public static native void internal_native_set_mGearRatios(long this_addr, long mGearRatios_addr);

    public ArrayFloat get_mReverseGearRatios() {
        long pointer = internal_native_get_mReverseGearRatios((long) getNativeData().getCPointer());
        if (pointer == 0)
            return null;
        if (ArrayFloat_TEMP_GEN_1 == null)
            ArrayFloat_TEMP_GEN_1 = new ArrayFloat((byte) 1, (char) 1);
        ArrayFloat_TEMP_GEN_1.getNativeData().reset(pointer, false);
        return ArrayFloat_TEMP_GEN_1;
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
return (jlong)&nativeObject->mReverseGearRatios;
*/
    public static native long internal_native_get_mReverseGearRatios(long this_addr);

    public void set_mReverseGearRatios(ArrayFloat mReverseGearRatios) {
        internal_native_set_mReverseGearRatios((long) getNativeData().getCPointer(), (long) (mReverseGearRatios != null ? mReverseGearRatios.getNativeData().getCPointer() : 0));
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
nativeObject->mReverseGearRatios = *((ArrayFloat*)mReverseGearRatios_addr);
*/
    public static native void internal_native_set_mReverseGearRatios(long this_addr, long mReverseGearRatios_addr);

    public float get_mSwitchTime() {
        return internal_native_get_mSwitchTime((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
return nativeObject->mSwitchTime;
*/
    public static native float internal_native_get_mSwitchTime(long this_addr);

    public void set_mSwitchTime(float mSwitchTime) {
        internal_native_set_mSwitchTime((long) getNativeData().getCPointer(), mSwitchTime);
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
nativeObject->mSwitchTime = mSwitchTime;
*/
    public static native void internal_native_set_mSwitchTime(long this_addr, float mSwitchTime);

    public float get_mClutchReleaseTime() {
        return internal_native_get_mClutchReleaseTime((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
return nativeObject->mClutchReleaseTime;
*/
    public static native float internal_native_get_mClutchReleaseTime(long this_addr);

    public void set_mClutchReleaseTime(float mClutchReleaseTime) {
        internal_native_set_mClutchReleaseTime((long) getNativeData().getCPointer(), mClutchReleaseTime);
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
nativeObject->mClutchReleaseTime = mClutchReleaseTime;
*/
    public static native void internal_native_set_mClutchReleaseTime(long this_addr, float mClutchReleaseTime);

    public float get_mSwitchLatency() {
        return internal_native_get_mSwitchLatency((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
return nativeObject->mSwitchLatency;
*/
    public static native float internal_native_get_mSwitchLatency(long this_addr);

    public void set_mSwitchLatency(float mSwitchLatency) {
        internal_native_set_mSwitchLatency((long) getNativeData().getCPointer(), mSwitchLatency);
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
nativeObject->mSwitchLatency = mSwitchLatency;
*/
    public static native void internal_native_set_mSwitchLatency(long this_addr, float mSwitchLatency);

    public float get_mShiftUpRPM() {
        return internal_native_get_mShiftUpRPM((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
return nativeObject->mShiftUpRPM;
*/
    public static native float internal_native_get_mShiftUpRPM(long this_addr);

    public void set_mShiftUpRPM(float mShiftUpRPM) {
        internal_native_set_mShiftUpRPM((long) getNativeData().getCPointer(), mShiftUpRPM);
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
nativeObject->mShiftUpRPM = mShiftUpRPM;
*/
    public static native void internal_native_set_mShiftUpRPM(long this_addr, float mShiftUpRPM);

    public float get_mShiftDownRPM() {
        return internal_native_get_mShiftDownRPM((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
return nativeObject->mShiftDownRPM;
*/
    public static native float internal_native_get_mShiftDownRPM(long this_addr);

    public void set_mShiftDownRPM(float mShiftDownRPM) {
        internal_native_set_mShiftDownRPM((long) getNativeData().getCPointer(), mShiftDownRPM);
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
nativeObject->mShiftDownRPM = mShiftDownRPM;
*/
    public static native void internal_native_set_mShiftDownRPM(long this_addr, float mShiftDownRPM);

    public float get_mClutchStrength() {
        return internal_native_get_mClutchStrength((long) getNativeData().getCPointer());
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
return nativeObject->mClutchStrength;
*/
    public static native float internal_native_get_mClutchStrength(long this_addr);

    public void set_mClutchStrength(float mClutchStrength) {
        internal_native_set_mClutchStrength((long) getNativeData().getCPointer(), mClutchStrength);
    }

    /*[-JNI;-NATIVE]
VehicleTransmissionSettings* nativeObject = (VehicleTransmissionSettings*)this_addr;
nativeObject->mClutchStrength = mClutchStrength;
*/
    public static native void internal_native_set_mClutchStrength(long this_addr, float mClutchStrength);
}
