/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.vehicle;

import jolt.idl.IDLBase;

public class VehicleCollisionTester extends IDLBase {

    static public final VehicleCollisionTester NULL = VehicleCollisionTester.createInstance();

    static public final VehicleCollisionTester T_01 = VehicleCollisionTester.createInstance();

    static public final VehicleCollisionTester T_02 = VehicleCollisionTester.createInstance();

    static public final VehicleCollisionTester T_03 = VehicleCollisionTester.createInstance();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleCollisionTester(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleCollisionTester createInstance() {
        return new VehicleCollisionTester((byte) 0, (char) 0);
    }

    public int GetRefCount() {
        return internal_native_GetRefCount(native_address);
    }

    /*[-JNI;-NATIVE]
VehicleCollisionTester* nativeObject = (VehicleCollisionTester*)this_addr;
return nativeObject->GetRefCount();
*/
    public static native int internal_native_GetRefCount(long this_addr);

    public void AddRef() {
        internal_native_AddRef(native_address);
    }

    /*[-JNI;-NATIVE]
VehicleCollisionTester* nativeObject = (VehicleCollisionTester*)this_addr;
nativeObject->AddRef();
*/
    public static native void internal_native_AddRef(long this_addr);

    public void Release() {
        internal_native_Release(native_address);
    }

    /*[-JNI;-NATIVE]
VehicleCollisionTester* nativeObject = (VehicleCollisionTester*)this_addr;
nativeObject->Release();
*/
    public static native void internal_native_Release(long this_addr);
}
