/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.vehicle;

public class VehicleCollisionTesterCastCylinder extends VehicleCollisionTester {

    static public final VehicleCollisionTesterCastCylinder NULL = VehicleCollisionTesterCastCylinder.native_new();

    static public final VehicleCollisionTesterCastCylinder T_01 = VehicleCollisionTesterCastCylinder.native_new();

    static public final VehicleCollisionTesterCastCylinder T_02 = VehicleCollisionTesterCastCylinder.native_new();

    static public final VehicleCollisionTesterCastCylinder T_03 = VehicleCollisionTesterCastCylinder.native_new();

    public VehicleCollisionTesterCastCylinder(int inObjectLayer, float inConvexRadiusFraction) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_int_float(inObjectLayer, inConvexRadiusFraction);
        internal_reset(addr, false);
    }

    /*[-JNI;-NATIVE]
return (jlong)new VehicleCollisionTesterCastCylinder(inObjectLayer, (float)inConvexRadiusFraction);
*/
    public static native long internal_native_create_int_float(int inObjectLayer, float inConvexRadiusFraction);

    public VehicleCollisionTesterCastCylinder(int inObjectLayer) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_int(inObjectLayer);
        internal_reset(addr, false);
    }

    /*[-JNI;-NATIVE]
return (jlong)new VehicleCollisionTesterCastCylinder(inObjectLayer);
*/
    public static native long internal_native_create_int(int inObjectLayer);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleCollisionTesterCastCylinder(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleCollisionTesterCastCylinder native_new() {
        return new VehicleCollisionTesterCastCylinder((byte) 0, (char) 0);
    }
}
