/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package jolt.physics.vehicle;

public class WheelSettingsTV extends WheelSettings {

    static public final WheelSettingsTV NULL = WheelSettingsTV.native_new();

    static public final WheelSettingsTV T_01 = WheelSettingsTV.native_new();

    static public final WheelSettingsTV T_02 = WheelSettingsTV.native_new();

    static public final WheelSettingsTV T_03 = WheelSettingsTV.native_new();

    public WheelSettingsTV() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, false);
    }

    /*[-JNI;-NATIVE]
return (jlong)new WheelSettingsTV();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WheelSettingsTV(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static WheelSettingsTV native_new() {
        return new WheelSettingsTV((byte) 0, (char) 0);
    }

    public float get_mLongitudinalFriction() {
        return internal_native_get_mLongitudinalFriction(native_address);
    }

    /*[-JNI;-NATIVE]
WheelSettingsTV* nativeObject = (WheelSettingsTV*)this_addr;
return nativeObject->mLongitudinalFriction;
*/
    public static native float internal_native_get_mLongitudinalFriction(long this_addr);

    public void set_mLongitudinalFriction(float mLongitudinalFriction) {
        internal_native_set_mLongitudinalFriction(native_address, mLongitudinalFriction);
    }

    /*[-JNI;-NATIVE]
WheelSettingsTV* nativeObject = (WheelSettingsTV*)this_addr;
nativeObject->mLongitudinalFriction = mLongitudinalFriction;
*/
    public static native void internal_native_set_mLongitudinalFriction(long this_addr, float mLongitudinalFriction);

    public float get_mLateralFriction() {
        return internal_native_get_mLateralFriction(native_address);
    }

    /*[-JNI;-NATIVE]
WheelSettingsTV* nativeObject = (WheelSettingsTV*)this_addr;
return nativeObject->mLateralFriction;
*/
    public static native float internal_native_get_mLateralFriction(long this_addr);

    public void set_mLateralFriction(float mLateralFriction) {
        internal_native_set_mLateralFriction(native_address, mLateralFriction);
    }

    /*[-JNI;-NATIVE]
WheelSettingsTV* nativeObject = (WheelSettingsTV*)this_addr;
nativeObject->mLateralFriction = mLateralFriction;
*/
    public static native void internal_native_set_mLateralFriction(long this_addr, float mLateralFriction);
}
